# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from copytrade import copytrade_pb2 as copytrade_dot_copytrade__pb2
from monitor import monitor_pb2 as monitor_dot_monitor__pb2
from sms import sms_pb2 as sms_dot_sms__pb2


class MonitorSrvStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetBrokerList = channel.unary_unary(
        '/monitor.MonitorSrv/GetBrokerList',
        request_serializer=copytrade_dot_copytrade__pb2.Empty.SerializeToString,
        response_deserializer=monitor_dot_monitor__pb2.GetBrokerListReply.FromString,
        )
    self.GetSymbolList = channel.unary_unary(
        '/monitor.MonitorSrv/GetSymbolList',
        request_serializer=copytrade_dot_copytrade__pb2.Empty.SerializeToString,
        response_deserializer=monitor_dot_monitor__pb2.GetSymbolListReply.FromString,
        )
    self.PageSymbol = channel.unary_unary(
        '/monitor.MonitorSrv/PageSymbol',
        request_serializer=monitor_dot_monitor__pb2.PageSymbolRequest.SerializeToString,
        response_deserializer=monitor_dot_monitor__pb2.PageSymbolReply.FromString,
        )
    self.PageFollow = channel.unary_unary(
        '/monitor.MonitorSrv/PageFollow',
        request_serializer=monitor_dot_monitor__pb2.PageFollowRequest.SerializeToString,
        response_deserializer=monitor_dot_monitor__pb2.PageFollowReply.FromString,
        )
    self.PageFollowOrder = channel.unary_unary(
        '/monitor.MonitorSrv/PageFollowOrder',
        request_serializer=monitor_dot_monitor__pb2.PageFollowOrderRequest.SerializeToString,
        response_deserializer=monitor_dot_monitor__pb2.PageFollowOrderReply.FromString,
        )
    self.PageErrorLog = channel.unary_unary(
        '/monitor.MonitorSrv/PageErrorLog',
        request_serializer=monitor_dot_monitor__pb2.PageErrorLogRequest.SerializeToString,
        response_deserializer=monitor_dot_monitor__pb2.PageErrorLogReply.FromString,
        )
    self.PageTrade = channel.unary_unary(
        '/monitor.MonitorSrv/PageTrade',
        request_serializer=monitor_dot_monitor__pb2.PageTradeRequest.SerializeToString,
        response_deserializer=monitor_dot_monitor__pb2.PageTradeReply.FromString,
        )
    self.PageUser = channel.unary_unary(
        '/monitor.MonitorSrv/PageUser',
        request_serializer=monitor_dot_monitor__pb2.PageUserRequest.SerializeToString,
        response_deserializer=monitor_dot_monitor__pb2.PageUserReply.FromString,
        )
    self.UpdateErrorLog = channel.unary_unary(
        '/monitor.MonitorSrv/UpdateErrorLog',
        request_serializer=copytrade_dot_copytrade__pb2.FollowOrderErrorLog.SerializeToString,
        response_deserializer=copytrade_dot_copytrade__pb2.FollowOrderErrorLog.FromString,
        )
    self.WarnError = channel.unary_unary(
        '/monitor.MonitorSrv/WarnError',
        request_serializer=copytrade_dot_copytrade__pb2.FollowOrderErrorLog.SerializeToString,
        response_deserializer=copytrade_dot_copytrade__pb2.Empty.FromString,
        )
    self.SubscribeErrorLog = channel.unary_stream(
        '/monitor.MonitorSrv/SubscribeErrorLog',
        request_serializer=monitor_dot_monitor__pb2.Empty.SerializeToString,
        response_deserializer=copytrade_dot_copytrade__pb2.FollowOrderErrorLog.FromString,
        )
    self.TriggerErrorLog = channel.unary_unary(
        '/monitor.MonitorSrv/TriggerErrorLog',
        request_serializer=monitor_dot_monitor__pb2.Empty.SerializeToString,
        response_deserializer=monitor_dot_monitor__pb2.Empty.FromString,
        )
    self.GetStatistics = channel.unary_unary(
        '/monitor.MonitorSrv/GetStatistics',
        request_serializer=monitor_dot_monitor__pb2.GetStatisticsRequest.SerializeToString,
        response_deserializer=monitor_dot_monitor__pb2.GetStatisticsReply.FromString,
        )
    self.GetUserAccount = channel.unary_unary(
        '/monitor.MonitorSrv/GetUserAccount',
        request_serializer=monitor_dot_monitor__pb2.GetUserAccountRequest.SerializeToString,
        response_deserializer=copytrade_dot_copytrade__pb2.UserAccount.FromString,
        )
    self.SendSms = channel.unary_unary(
        '/monitor.MonitorSrv/SendSms',
        request_serializer=sms_dot_sms__pb2.SendRequest.SerializeToString,
        response_deserializer=copytrade_dot_copytrade__pb2.Empty.FromString,
        )
    self.PageFollowerRiskControl = channel.unary_unary(
        '/monitor.MonitorSrv/PageFollowerRiskControl',
        request_serializer=monitor_dot_monitor__pb2.PageFollowerRiskControlRequest.SerializeToString,
        response_deserializer=monitor_dot_monitor__pb2.PageFollowerRiskControlReply.FromString,
        )
    self.PageFollowerRiskControlForTrader = channel.unary_unary(
        '/monitor.MonitorSrv/PageFollowerRiskControlForTrader',
        request_serializer=monitor_dot_monitor__pb2.PageFollowerRiskControlForTraderRequest.SerializeToString,
        response_deserializer=monitor_dot_monitor__pb2.PageFollowerRiskControlForTraderReply.FromString,
        )
    self.PageFollowerRiskControlForSymbol = channel.unary_unary(
        '/monitor.MonitorSrv/PageFollowerRiskControlForSymbol',
        request_serializer=monitor_dot_monitor__pb2.PageFollowerRiskControlForSymbolRequest.SerializeToString,
        response_deserializer=monitor_dot_monitor__pb2.PageFollowerRiskControlForSymbolReply.FromString,
        )
    self.GetFollowUserListByTrader = channel.unary_unary(
        '/monitor.MonitorSrv/GetFollowUserListByTrader',
        request_serializer=monitor_dot_monitor__pb2.GetUserAccountRequest.SerializeToString,
        response_deserializer=monitor_dot_monitor__pb2.GetFollowUserListByTraderReply.FromString,
        )


class MonitorSrvServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetBrokerList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSymbolList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PageSymbol(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PageFollow(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PageFollowOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PageErrorLog(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PageTrade(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PageUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateErrorLog(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WarnError(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubscribeErrorLog(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TriggerErrorLog(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStatistics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendSms(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PageFollowerRiskControl(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PageFollowerRiskControlForTrader(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PageFollowerRiskControlForSymbol(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFollowUserListByTrader(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MonitorSrvServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetBrokerList': grpc.unary_unary_rpc_method_handler(
          servicer.GetBrokerList,
          request_deserializer=copytrade_dot_copytrade__pb2.Empty.FromString,
          response_serializer=monitor_dot_monitor__pb2.GetBrokerListReply.SerializeToString,
      ),
      'GetSymbolList': grpc.unary_unary_rpc_method_handler(
          servicer.GetSymbolList,
          request_deserializer=copytrade_dot_copytrade__pb2.Empty.FromString,
          response_serializer=monitor_dot_monitor__pb2.GetSymbolListReply.SerializeToString,
      ),
      'PageSymbol': grpc.unary_unary_rpc_method_handler(
          servicer.PageSymbol,
          request_deserializer=monitor_dot_monitor__pb2.PageSymbolRequest.FromString,
          response_serializer=monitor_dot_monitor__pb2.PageSymbolReply.SerializeToString,
      ),
      'PageFollow': grpc.unary_unary_rpc_method_handler(
          servicer.PageFollow,
          request_deserializer=monitor_dot_monitor__pb2.PageFollowRequest.FromString,
          response_serializer=monitor_dot_monitor__pb2.PageFollowReply.SerializeToString,
      ),
      'PageFollowOrder': grpc.unary_unary_rpc_method_handler(
          servicer.PageFollowOrder,
          request_deserializer=monitor_dot_monitor__pb2.PageFollowOrderRequest.FromString,
          response_serializer=monitor_dot_monitor__pb2.PageFollowOrderReply.SerializeToString,
      ),
      'PageErrorLog': grpc.unary_unary_rpc_method_handler(
          servicer.PageErrorLog,
          request_deserializer=monitor_dot_monitor__pb2.PageErrorLogRequest.FromString,
          response_serializer=monitor_dot_monitor__pb2.PageErrorLogReply.SerializeToString,
      ),
      'PageTrade': grpc.unary_unary_rpc_method_handler(
          servicer.PageTrade,
          request_deserializer=monitor_dot_monitor__pb2.PageTradeRequest.FromString,
          response_serializer=monitor_dot_monitor__pb2.PageTradeReply.SerializeToString,
      ),
      'PageUser': grpc.unary_unary_rpc_method_handler(
          servicer.PageUser,
          request_deserializer=monitor_dot_monitor__pb2.PageUserRequest.FromString,
          response_serializer=monitor_dot_monitor__pb2.PageUserReply.SerializeToString,
      ),
      'UpdateErrorLog': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateErrorLog,
          request_deserializer=copytrade_dot_copytrade__pb2.FollowOrderErrorLog.FromString,
          response_serializer=copytrade_dot_copytrade__pb2.FollowOrderErrorLog.SerializeToString,
      ),
      'WarnError': grpc.unary_unary_rpc_method_handler(
          servicer.WarnError,
          request_deserializer=copytrade_dot_copytrade__pb2.FollowOrderErrorLog.FromString,
          response_serializer=copytrade_dot_copytrade__pb2.Empty.SerializeToString,
      ),
      'SubscribeErrorLog': grpc.unary_stream_rpc_method_handler(
          servicer.SubscribeErrorLog,
          request_deserializer=monitor_dot_monitor__pb2.Empty.FromString,
          response_serializer=copytrade_dot_copytrade__pb2.FollowOrderErrorLog.SerializeToString,
      ),
      'TriggerErrorLog': grpc.unary_unary_rpc_method_handler(
          servicer.TriggerErrorLog,
          request_deserializer=monitor_dot_monitor__pb2.Empty.FromString,
          response_serializer=monitor_dot_monitor__pb2.Empty.SerializeToString,
      ),
      'GetStatistics': grpc.unary_unary_rpc_method_handler(
          servicer.GetStatistics,
          request_deserializer=monitor_dot_monitor__pb2.GetStatisticsRequest.FromString,
          response_serializer=monitor_dot_monitor__pb2.GetStatisticsReply.SerializeToString,
      ),
      'GetUserAccount': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserAccount,
          request_deserializer=monitor_dot_monitor__pb2.GetUserAccountRequest.FromString,
          response_serializer=copytrade_dot_copytrade__pb2.UserAccount.SerializeToString,
      ),
      'SendSms': grpc.unary_unary_rpc_method_handler(
          servicer.SendSms,
          request_deserializer=sms_dot_sms__pb2.SendRequest.FromString,
          response_serializer=copytrade_dot_copytrade__pb2.Empty.SerializeToString,
      ),
      'PageFollowerRiskControl': grpc.unary_unary_rpc_method_handler(
          servicer.PageFollowerRiskControl,
          request_deserializer=monitor_dot_monitor__pb2.PageFollowerRiskControlRequest.FromString,
          response_serializer=monitor_dot_monitor__pb2.PageFollowerRiskControlReply.SerializeToString,
      ),
      'PageFollowerRiskControlForTrader': grpc.unary_unary_rpc_method_handler(
          servicer.PageFollowerRiskControlForTrader,
          request_deserializer=monitor_dot_monitor__pb2.PageFollowerRiskControlForTraderRequest.FromString,
          response_serializer=monitor_dot_monitor__pb2.PageFollowerRiskControlForTraderReply.SerializeToString,
      ),
      'PageFollowerRiskControlForSymbol': grpc.unary_unary_rpc_method_handler(
          servicer.PageFollowerRiskControlForSymbol,
          request_deserializer=monitor_dot_monitor__pb2.PageFollowerRiskControlForSymbolRequest.FromString,
          response_serializer=monitor_dot_monitor__pb2.PageFollowerRiskControlForSymbolReply.SerializeToString,
      ),
      'GetFollowUserListByTrader': grpc.unary_unary_rpc_method_handler(
          servicer.GetFollowUserListByTrader,
          request_deserializer=monitor_dot_monitor__pb2.GetUserAccountRequest.FromString,
          response_serializer=monitor_dot_monitor__pb2.GetFollowUserListByTraderReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'monitor.MonitorSrv', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
