# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
import sys
sys.path.append("../../proto")
from mt4api import mt4api_pb2 as mt4api_dot_mt4api__pb2
from tradesignal import tradesignal_pb2 as tradesignal_dot_tradesignal__pb2


class MT4APISrvStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SubscribeMT4API = channel.unary_stream(
        '/mt4api.MT4APISrv/SubscribeMT4API',
        request_serializer=mt4api_dot_mt4api__pb2.Empty.SerializeToString,
        response_deserializer=mt4api_dot_mt4api__pb2.APISignal.FromString,
        )
    self.SubscribeQuotes = channel.unary_stream(
        '/mt4api.MT4APISrv/SubscribeQuotes',
        request_serializer=mt4api_dot_mt4api__pb2.Empty.SerializeToString,
        response_deserializer=mt4api_dot_mt4api__pb2.AccountQuotes.FromString,
        )
    self.OpenPosition = channel.stream_stream(
        '/mt4api.MT4APISrv/OpenPosition',
        request_serializer=mt4api_dot_mt4api__pb2.PositionRequest.SerializeToString,
        response_deserializer=mt4api_dot_mt4api__pb2.PositionReply.FromString,
        )
    self.ClosePosition = channel.stream_stream(
        '/mt4api.MT4APISrv/ClosePosition',
        request_serializer=mt4api_dot_mt4api__pb2.PositionRequest.SerializeToString,
        response_deserializer=mt4api_dot_mt4api__pb2.PositionReply.FromString,
        )
    self.UpdatePosition = channel.stream_stream(
        '/mt4api.MT4APISrv/UpdatePosition',
        request_serializer=mt4api_dot_mt4api__pb2.PositionRequest.SerializeToString,
        response_deserializer=mt4api_dot_mt4api__pb2.PositionReply.FromString,
        )
    self.SyncAck = channel.unary_unary(
        '/mt4api.MT4APISrv/SyncAck',
        request_serializer=mt4api_dot_mt4api__pb2.AccountRequest.SerializeToString,
        response_deserializer=mt4api_dot_mt4api__pb2.SuccessReply.FromString,
        )
    self.SyncPosition = channel.unary_unary(
        '/mt4api.MT4APISrv/SyncPosition',
        request_serializer=mt4api_dot_mt4api__pb2.AccountRequest.SerializeToString,
        response_deserializer=mt4api_dot_mt4api__pb2.TradeSignalListReply.FromString,
        )
    self.SyncCloseSingal = channel.unary_unary(
        '/mt4api.MT4APISrv/SyncCloseSingal',
        request_serializer=mt4api_dot_mt4api__pb2.SyncCloseSignalRequest.SerializeToString,
        response_deserializer=tradesignal_dot_tradesignal__pb2.TradeSignal.FromString,
        )
    self.SyncHistoryTradesByIndex = channel.unary_unary(
        '/mt4api.MT4APISrv/SyncHistoryTradesByIndex',
        request_serializer=mt4api_dot_mt4api__pb2.SyncHistoryRequest.SerializeToString,
        response_deserializer=mt4api_dot_mt4api__pb2.TradeSignalListReply.FromString,
        )
    self.SyncHistoryTradesByTime = channel.unary_unary(
        '/mt4api.MT4APISrv/SyncHistoryTradesByTime',
        request_serializer=mt4api_dot_mt4api__pb2.SyncHistoryRequest.SerializeToString,
        response_deserializer=mt4api_dot_mt4api__pb2.TradeSignalListReply.FromString,
        )


class MT4APISrvServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SubscribeMT4API(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubscribeQuotes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OpenPosition(self, request_iterator, context):
    """开仓
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ClosePosition(self, request_iterator, context):
    """平仓
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdatePosition(self, request_iterator, context):
    """修改持仓单
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SyncAck(self, request, context):
    """初始化完成 ack
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SyncPosition(self, request, context):
    """主动请求持仓单列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SyncCloseSingal(self, request, context):
    """根据平仓单 tradeid 获取平仓订单
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SyncHistoryTradesByIndex(self, request, context):
    """根据index获取历史订单
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SyncHistoryTradesByTime(self, request, context):
    """根据starttime endtime 获取历史订单
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MT4APISrvServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SubscribeMT4API': grpc.unary_stream_rpc_method_handler(
          servicer.SubscribeMT4API,
          request_deserializer=mt4api_dot_mt4api__pb2.Empty.FromString,
          response_serializer=mt4api_dot_mt4api__pb2.APISignal.SerializeToString,
      ),
      'SubscribeQuotes': grpc.unary_stream_rpc_method_handler(
          servicer.SubscribeQuotes,
          request_deserializer=mt4api_dot_mt4api__pb2.Empty.FromString,
          response_serializer=mt4api_dot_mt4api__pb2.AccountQuotes.SerializeToString,
      ),
      'OpenPosition': grpc.stream_stream_rpc_method_handler(
          servicer.OpenPosition,
          request_deserializer=mt4api_dot_mt4api__pb2.PositionRequest.FromString,
          response_serializer=mt4api_dot_mt4api__pb2.PositionReply.SerializeToString,
      ),
      'ClosePosition': grpc.stream_stream_rpc_method_handler(
          servicer.ClosePosition,
          request_deserializer=mt4api_dot_mt4api__pb2.PositionRequest.FromString,
          response_serializer=mt4api_dot_mt4api__pb2.PositionReply.SerializeToString,
      ),
      'UpdatePosition': grpc.stream_stream_rpc_method_handler(
          servicer.UpdatePosition,
          request_deserializer=mt4api_dot_mt4api__pb2.PositionRequest.FromString,
          response_serializer=mt4api_dot_mt4api__pb2.PositionReply.SerializeToString,
      ),
      'SyncAck': grpc.unary_unary_rpc_method_handler(
          servicer.SyncAck,
          request_deserializer=mt4api_dot_mt4api__pb2.AccountRequest.FromString,
          response_serializer=mt4api_dot_mt4api__pb2.SuccessReply.SerializeToString,
      ),
      'SyncPosition': grpc.unary_unary_rpc_method_handler(
          servicer.SyncPosition,
          request_deserializer=mt4api_dot_mt4api__pb2.AccountRequest.FromString,
          response_serializer=mt4api_dot_mt4api__pb2.TradeSignalListReply.SerializeToString,
      ),
      'SyncCloseSingal': grpc.unary_unary_rpc_method_handler(
          servicer.SyncCloseSingal,
          request_deserializer=mt4api_dot_mt4api__pb2.SyncCloseSignalRequest.FromString,
          response_serializer=tradesignal_dot_tradesignal__pb2.TradeSignal.SerializeToString,
      ),
      'SyncHistoryTradesByIndex': grpc.unary_unary_rpc_method_handler(
          servicer.SyncHistoryTradesByIndex,
          request_deserializer=mt4api_dot_mt4api__pb2.SyncHistoryRequest.FromString,
          response_serializer=mt4api_dot_mt4api__pb2.TradeSignalListReply.SerializeToString,
      ),
      'SyncHistoryTradesByTime': grpc.unary_unary_rpc_method_handler(
          servicer.SyncHistoryTradesByTime,
          request_deserializer=mt4api_dot_mt4api__pb2.SyncHistoryRequest.FromString,
          response_serializer=mt4api_dot_mt4api__pb2.TradeSignalListReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'mt4api.MT4APISrv', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
