# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
import sys
sys.path.append("../../proto")
from social3 import social3Message_pb2 as social3_dot_social3Message__pb2


class SocialServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.BlogAdd = channel.unary_unary(
        '/social3.SocialService/BlogAdd',
        request_serializer=social3_dot_social3Message__pb2.BlogAddInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommandOutput.FromString,
        )
    self.BlogShare = channel.unary_unary(
        '/social3.SocialService/BlogShare',
        request_serializer=social3_dot_social3Message__pb2.BlogShareInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommandOutput.FromString,
        )
    self.BlogsByAttention = channel.unary_unary(
        '/social3.SocialService/BlogsByAttention',
        request_serializer=social3_dot_social3Message__pb2.BlogQueryInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.BlogQueryOutput.FromString,
        )
    self.BlogsByHot = channel.unary_unary(
        '/social3.SocialService/BlogsByHot',
        request_serializer=social3_dot_social3Message__pb2.BlogQueryInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.BlogQueryOutput.FromString,
        )
    self.BlogsByNews = channel.unary_unary(
        '/social3.SocialService/BlogsByNews',
        request_serializer=social3_dot_social3Message__pb2.BlogQueryInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.BlogQueryOutput.FromString,
        )
    self.BlogsByElite = channel.unary_unary(
        '/social3.SocialService/BlogsByElite',
        request_serializer=social3_dot_social3Message__pb2.BlogQueryInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.BlogQueryOutput.FromString,
        )
    self.BlogsByTrade = channel.unary_unary(
        '/social3.SocialService/BlogsByTrade',
        request_serializer=social3_dot_social3Message__pb2.BlogQueryInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.BlogQueryOutput.FromString,
        )
    self.BlogsByMedia = channel.unary_unary(
        '/social3.SocialService/BlogsByMedia',
        request_serializer=social3_dot_social3Message__pb2.BlogQueryInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.BlogQueryOutput.FromString,
        )
    self.BlogsByBroker = channel.unary_unary(
        '/social3.SocialService/BlogsByBroker',
        request_serializer=social3_dot_social3Message__pb2.BlogQueryInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.BlogQueryOutput.FromString,
        )
    self.BlogsByAnalyst = channel.unary_unary(
        '/social3.SocialService/BlogsByAnalyst',
        request_serializer=social3_dot_social3Message__pb2.BlogQueryInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.BlogQueryOutput.FromString,
        )
    self.BlogsByUser = channel.unary_unary(
        '/social3.SocialService/BlogsByUser',
        request_serializer=social3_dot_social3Message__pb2.BlogsByUserInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.BlogQueryOutput.FromString,
        )
    self.BlogsBySearch = channel.unary_unary(
        '/social3.SocialService/BlogsBySearch',
        request_serializer=social3_dot_social3Message__pb2.BlogsBySearchInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.BlogQueryOutput.FromString,
        )
    self.BlogByDetail = channel.unary_unary(
        '/social3.SocialService/BlogByDetail',
        request_serializer=social3_dot_social3Message__pb2.BlogByDetailInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.BlogQueryItemOutput.FromString,
        )
    self.BlogsByFinancialNews = channel.unary_unary(
        '/social3.SocialService/BlogsByFinancialNews',
        request_serializer=social3_dot_social3Message__pb2.BlogsByFinancialNewsInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.BlogQueryOutput.FromString,
        )
    self.FinancialCalendarsByDate = channel.unary_unary(
        '/social3.SocialService/FinancialCalendarsByDate',
        request_serializer=social3_dot_social3Message__pb2.FinancialCalendarsByDateInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.FinancialCalendarsByDateOutput.FromString,
        )
    self.FinancialCalendarByDetail = channel.unary_unary(
        '/social3.SocialService/FinancialCalendarByDetail',
        request_serializer=social3_dot_social3Message__pb2.FinancialCalendarByDetailInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.FinancialCalendarByDetailOutput.FromString,
        )
    self.FirewireCouriersByDate = channel.unary_unary(
        '/social3.SocialService/FirewireCouriersByDate',
        request_serializer=social3_dot_social3Message__pb2.FirewireCouriersByDateInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.FirewireCouriersByDateOutput.FromString,
        )
    self.BlogDel = channel.unary_unary(
        '/social3.SocialService/BlogDel',
        request_serializer=social3_dot_social3Message__pb2.BlogDelInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommandOutput.FromString,
        )
    self.BlogTop = channel.unary_unary(
        '/social3.SocialService/BlogTop',
        request_serializer=social3_dot_social3Message__pb2.BlogTopInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommandOutput.FromString,
        )
    self.BlogElite = channel.unary_unary(
        '/social3.SocialService/BlogElite',
        request_serializer=social3_dot_social3Message__pb2.BlogEliteInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommandOutput.FromString,
        )
    self.BlogHandpick = channel.unary_unary(
        '/social3.SocialService/BlogHandpick',
        request_serializer=social3_dot_social3Message__pb2.BlogHandpickInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommandOutput.FromString,
        )
    self.BlogsByManageList = channel.unary_unary(
        '/social3.SocialService/BlogsByManageList',
        request_serializer=social3_dot_social3Message__pb2.BlogsByManageListInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.BlogsByManageListOutput.FromString,
        )
    self.BlogByCat = channel.unary_unary(
        '/social3.SocialService/BlogByCat',
        request_serializer=social3_dot_social3Message__pb2.BlogByCatInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.BlogByCatOutput.FromString,
        )
    self.BlogsByAll = channel.unary_unary(
        '/social3.SocialService/BlogsByAll',
        request_serializer=social3_dot_social3Message__pb2.BlogQueryInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.BlogQueryOutput.FromString,
        )
    self.BlogsByPostType = channel.unary_unary(
        '/social3.SocialService/BlogsByPostType',
        request_serializer=social3_dot_social3Message__pb2.BlogsByPostTypeInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.BlogQueryOutput.FromString,
        )
    self.BlogsByBlogType = channel.unary_unary(
        '/social3.SocialService/BlogsByBlogType',
        request_serializer=social3_dot_social3Message__pb2.BlogsByBlogTypeInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.BlogQueryOutput.FromString,
        )
    self.CommentAdd = channel.unary_unary(
        '/social3.SocialService/CommentAdd',
        request_serializer=social3_dot_social3Message__pb2.CommentAddInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommandOutput.FromString,
        )
    self.CommentsByObject = channel.unary_unary(
        '/social3.SocialService/CommentsByObject',
        request_serializer=social3_dot_social3Message__pb2.CommentsByObjectInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommentsByObjectOutput.FromString,
        )
    self.CommentsByUser = channel.unary_unary(
        '/social3.SocialService/CommentsByUser',
        request_serializer=social3_dot_social3Message__pb2.CommentsByUserInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommentsByUserOutput.FromString,
        )
    self.CommentDel = channel.unary_unary(
        '/social3.SocialService/CommentDel',
        request_serializer=social3_dot_social3Message__pb2.CommentDelInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommandOutput.FromString,
        )
    self.CommentsByManageList = channel.unary_unary(
        '/social3.SocialService/CommentsByManageList',
        request_serializer=social3_dot_social3Message__pb2.CommentsByManageListInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommentsByObjectOutput.FromString,
        )
    self.FavoriteAddDel = channel.unary_unary(
        '/social3.SocialService/FavoriteAddDel',
        request_serializer=social3_dot_social3Message__pb2.FavoriteAddDelInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommandOutput.FromString,
        )
    self.FavoritesByUser = channel.unary_unary(
        '/social3.SocialService/FavoritesByUser',
        request_serializer=social3_dot_social3Message__pb2.FavoritesByUserInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.FavoritesByUserOutput.FromString,
        )
    self.LikesAddDel = channel.unary_unary(
        '/social3.SocialService/LikesAddDel',
        request_serializer=social3_dot_social3Message__pb2.LikesAddDelInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommandOutput.FromString,
        )
    self.LikesesByObject = channel.unary_unary(
        '/social3.SocialService/LikesesByObject',
        request_serializer=social3_dot_social3Message__pb2.LikesesByObjectInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.LikesesByObjectOutput.FromString,
        )
    self.LikesesByUser = channel.unary_unary(
        '/social3.SocialService/LikesesByUser',
        request_serializer=social3_dot_social3Message__pb2.LikesesByUserInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.LikesesByUserOutput.FromString,
        )
    self.AttentionAddDel = channel.unary_unary(
        '/social3.SocialService/AttentionAddDel',
        request_serializer=social3_dot_social3Message__pb2.AttentionAddDelInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommandOutput.FromString,
        )
    self.AttentionForce = channel.unary_unary(
        '/social3.SocialService/AttentionForce',
        request_serializer=social3_dot_social3Message__pb2.AttentionForceInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommandOutput.FromString,
        )
    self.RelationshipsByUserAttention = channel.unary_unary(
        '/social3.SocialService/RelationshipsByUserAttention',
        request_serializer=social3_dot_social3Message__pb2.RelationshipsByUserBaseInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.RelationshipsByUserBaseOutput.FromString,
        )
    self.RelationshipsByUserFans = channel.unary_unary(
        '/social3.SocialService/RelationshipsByUserFans',
        request_serializer=social3_dot_social3Message__pb2.RelationshipsByUserBaseInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.RelationshipsByUserBaseOutput.FromString,
        )
    self.RelationshipsByUserToUser = channel.unary_unary(
        '/social3.SocialService/RelationshipsByUserToUser',
        request_serializer=social3_dot_social3Message__pb2.RelationshipsByUserToUserInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.RelationshipsByUserToUserOutput.FromString,
        )
    self.RelationshipsByUserToUsers = channel.unary_unary(
        '/social3.SocialService/RelationshipsByUserToUsers',
        request_serializer=social3_dot_social3Message__pb2.RelationshipsByUserToUsersInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.RelationshipsByUserToUsersOutput.FromString,
        )
    self.RelationshipsByUserAll = channel.unary_unary(
        '/social3.SocialService/RelationshipsByUserAll',
        request_serializer=social3_dot_social3Message__pb2.LongProtoDto.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.RelationshipsByUserAllOutput.FromString,
        )
    self.StarUsersByUserAttention = channel.unary_unary(
        '/social3.SocialService/StarUsersByUserAttention',
        request_serializer=social3_dot_social3Message__pb2.LongProtoDto.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.StarUsersOutput.FromString,
        )
    self.StarUsersByUserFans = channel.unary_unary(
        '/social3.SocialService/StarUsersByUserFans',
        request_serializer=social3_dot_social3Message__pb2.LongProtoDto.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.StarUsersOutput.FromString,
        )
    self.StarUsersBySystem = channel.unary_unary(
        '/social3.SocialService/StarUsersBySystem',
        request_serializer=social3_dot_social3Message__pb2.LongProtoDto.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.StarUsersOutput.FromString,
        )
    self.HotTopics = channel.unary_unary(
        '/social3.SocialService/HotTopics',
        request_serializer=social3_dot_social3Message__pb2.BaseQueryTopicInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.QueryTopicOutput.FromString,
        )
    self.TopicBlogs = channel.unary_unary(
        '/social3.SocialService/TopicBlogs',
        request_serializer=social3_dot_social3Message__pb2.BlogQueryInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.BlogQueryOutput.FromString,
        )
    self.UserInfoByUserId = channel.unary_unary(
        '/social3.SocialService/UserInfoByUserId',
        request_serializer=social3_dot_social3Message__pb2.LongProtoDto.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.UserInfoOutput.FromString,
        )
    self.UserSearch = channel.unary_unary(
        '/social3.SocialService/UserSearch',
        request_serializer=social3_dot_social3Message__pb2.UserSearchInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.UserSearchOutput.FromString,
        )
    self.UserStatusSet = channel.unary_unary(
        '/social3.SocialService/UserStatusSet',
        request_serializer=social3_dot_social3Message__pb2.UserStatusSetInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommandOutput.FromString,
        )
    self.UserStatusGet = channel.unary_unary(
        '/social3.SocialService/UserStatusGet',
        request_serializer=social3_dot_social3Message__pb2.UserStatusBaseInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.UserStatusOutput.FromString,
        )
    self.UserStatusClear = channel.unary_unary(
        '/social3.SocialService/UserStatusClear',
        request_serializer=social3_dot_social3Message__pb2.UserStatusBaseInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommandOutput.FromString,
        )
    self.AnnouncementsByAll = channel.unary_unary(
        '/social3.SocialService/AnnouncementsByAll',
        request_serializer=social3_dot_social3Message__pb2.PageInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.AnnouncementsByAllOutput.FromString,
        )
    self.AnnouncementsByManageList = channel.unary_unary(
        '/social3.SocialService/AnnouncementsByManageList',
        request_serializer=social3_dot_social3Message__pb2.AnnouncementsByManageListInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.AnnouncementsByManageListOutput.FromString,
        )
    self.AnnouncementAddUpdate = channel.unary_unary(
        '/social3.SocialService/AnnouncementAddUpdate',
        request_serializer=social3_dot_social3Message__pb2.AnnouncementAddUpdateInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommandOutput.FromString,
        )
    self.AnnouncementDel = channel.unary_unary(
        '/social3.SocialService/AnnouncementDel',
        request_serializer=social3_dot_social3Message__pb2.AnnouncementDelInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommandOutput.FromString,
        )
    self.RecommendationBlogsByLocation = channel.unary_unary(
        '/social3.SocialService/RecommendationBlogsByLocation',
        request_serializer=social3_dot_social3Message__pb2.RecommendationBlogsByLocationInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.RecommendationBlogsByLocationOutput.FromString,
        )
    self.RecommendationAddUpdate = channel.unary_unary(
        '/social3.SocialService/RecommendationAddUpdate',
        request_serializer=social3_dot_social3Message__pb2.RecommendationAddUpdateInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommandOutput.FromString,
        )
    self.RecommendationSort = channel.unary_unary(
        '/social3.SocialService/RecommendationSort',
        request_serializer=social3_dot_social3Message__pb2.RecommendationSortInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommandOutput.FromString,
        )
    self.RecommendationDel = channel.unary_unary(
        '/social3.SocialService/RecommendationDel',
        request_serializer=social3_dot_social3Message__pb2.RecommendationDelInput.SerializeToString,
        response_deserializer=social3_dot_social3Message__pb2.CommandOutput.FromString,
        )


class SocialServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def BlogAdd(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogShare(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogsByAttention(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogsByHot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogsByNews(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogsByElite(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogsByTrade(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogsByMedia(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogsByBroker(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogsByAnalyst(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogsByUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogsBySearch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogByDetail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogsByFinancialNews(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FinancialCalendarsByDate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FinancialCalendarByDetail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FirewireCouriersByDate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogDel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogTop(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogElite(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogHandpick(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogsByManageList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogByCat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogsByAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogsByPostType(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BlogsByBlogType(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CommentAdd(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CommentsByObject(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CommentsByUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CommentDel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CommentsByManageList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FavoriteAddDel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FavoritesByUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LikesAddDel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LikesesByObject(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LikesesByUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AttentionAddDel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AttentionForce(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RelationshipsByUserAttention(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RelationshipsByUserFans(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RelationshipsByUserToUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RelationshipsByUserToUsers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RelationshipsByUserAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StarUsersByUserAttention(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StarUsersByUserFans(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StarUsersBySystem(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HotTopics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TopicBlogs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UserInfoByUserId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UserSearch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UserStatusSet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UserStatusGet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UserStatusClear(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AnnouncementsByAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AnnouncementsByManageList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AnnouncementAddUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AnnouncementDel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RecommendationBlogsByLocation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RecommendationAddUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RecommendationSort(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RecommendationDel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SocialServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'BlogAdd': grpc.unary_unary_rpc_method_handler(
          servicer.BlogAdd,
          request_deserializer=social3_dot_social3Message__pb2.BlogAddInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommandOutput.SerializeToString,
      ),
      'BlogShare': grpc.unary_unary_rpc_method_handler(
          servicer.BlogShare,
          request_deserializer=social3_dot_social3Message__pb2.BlogShareInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommandOutput.SerializeToString,
      ),
      'BlogsByAttention': grpc.unary_unary_rpc_method_handler(
          servicer.BlogsByAttention,
          request_deserializer=social3_dot_social3Message__pb2.BlogQueryInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.BlogQueryOutput.SerializeToString,
      ),
      'BlogsByHot': grpc.unary_unary_rpc_method_handler(
          servicer.BlogsByHot,
          request_deserializer=social3_dot_social3Message__pb2.BlogQueryInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.BlogQueryOutput.SerializeToString,
      ),
      'BlogsByNews': grpc.unary_unary_rpc_method_handler(
          servicer.BlogsByNews,
          request_deserializer=social3_dot_social3Message__pb2.BlogQueryInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.BlogQueryOutput.SerializeToString,
      ),
      'BlogsByElite': grpc.unary_unary_rpc_method_handler(
          servicer.BlogsByElite,
          request_deserializer=social3_dot_social3Message__pb2.BlogQueryInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.BlogQueryOutput.SerializeToString,
      ),
      'BlogsByTrade': grpc.unary_unary_rpc_method_handler(
          servicer.BlogsByTrade,
          request_deserializer=social3_dot_social3Message__pb2.BlogQueryInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.BlogQueryOutput.SerializeToString,
      ),
      'BlogsByMedia': grpc.unary_unary_rpc_method_handler(
          servicer.BlogsByMedia,
          request_deserializer=social3_dot_social3Message__pb2.BlogQueryInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.BlogQueryOutput.SerializeToString,
      ),
      'BlogsByBroker': grpc.unary_unary_rpc_method_handler(
          servicer.BlogsByBroker,
          request_deserializer=social3_dot_social3Message__pb2.BlogQueryInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.BlogQueryOutput.SerializeToString,
      ),
      'BlogsByAnalyst': grpc.unary_unary_rpc_method_handler(
          servicer.BlogsByAnalyst,
          request_deserializer=social3_dot_social3Message__pb2.BlogQueryInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.BlogQueryOutput.SerializeToString,
      ),
      'BlogsByUser': grpc.unary_unary_rpc_method_handler(
          servicer.BlogsByUser,
          request_deserializer=social3_dot_social3Message__pb2.BlogsByUserInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.BlogQueryOutput.SerializeToString,
      ),
      'BlogsBySearch': grpc.unary_unary_rpc_method_handler(
          servicer.BlogsBySearch,
          request_deserializer=social3_dot_social3Message__pb2.BlogsBySearchInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.BlogQueryOutput.SerializeToString,
      ),
      'BlogByDetail': grpc.unary_unary_rpc_method_handler(
          servicer.BlogByDetail,
          request_deserializer=social3_dot_social3Message__pb2.BlogByDetailInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.BlogQueryItemOutput.SerializeToString,
      ),
      'BlogsByFinancialNews': grpc.unary_unary_rpc_method_handler(
          servicer.BlogsByFinancialNews,
          request_deserializer=social3_dot_social3Message__pb2.BlogsByFinancialNewsInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.BlogQueryOutput.SerializeToString,
      ),
      'FinancialCalendarsByDate': grpc.unary_unary_rpc_method_handler(
          servicer.FinancialCalendarsByDate,
          request_deserializer=social3_dot_social3Message__pb2.FinancialCalendarsByDateInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.FinancialCalendarsByDateOutput.SerializeToString,
      ),
      'FinancialCalendarByDetail': grpc.unary_unary_rpc_method_handler(
          servicer.FinancialCalendarByDetail,
          request_deserializer=social3_dot_social3Message__pb2.FinancialCalendarByDetailInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.FinancialCalendarByDetailOutput.SerializeToString,
      ),
      'FirewireCouriersByDate': grpc.unary_unary_rpc_method_handler(
          servicer.FirewireCouriersByDate,
          request_deserializer=social3_dot_social3Message__pb2.FirewireCouriersByDateInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.FirewireCouriersByDateOutput.SerializeToString,
      ),
      'BlogDel': grpc.unary_unary_rpc_method_handler(
          servicer.BlogDel,
          request_deserializer=social3_dot_social3Message__pb2.BlogDelInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommandOutput.SerializeToString,
      ),
      'BlogTop': grpc.unary_unary_rpc_method_handler(
          servicer.BlogTop,
          request_deserializer=social3_dot_social3Message__pb2.BlogTopInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommandOutput.SerializeToString,
      ),
      'BlogElite': grpc.unary_unary_rpc_method_handler(
          servicer.BlogElite,
          request_deserializer=social3_dot_social3Message__pb2.BlogEliteInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommandOutput.SerializeToString,
      ),
      'BlogHandpick': grpc.unary_unary_rpc_method_handler(
          servicer.BlogHandpick,
          request_deserializer=social3_dot_social3Message__pb2.BlogHandpickInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommandOutput.SerializeToString,
      ),
      'BlogsByManageList': grpc.unary_unary_rpc_method_handler(
          servicer.BlogsByManageList,
          request_deserializer=social3_dot_social3Message__pb2.BlogsByManageListInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.BlogsByManageListOutput.SerializeToString,
      ),
      'BlogByCat': grpc.unary_unary_rpc_method_handler(
          servicer.BlogByCat,
          request_deserializer=social3_dot_social3Message__pb2.BlogByCatInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.BlogByCatOutput.SerializeToString,
      ),
      'BlogsByAll': grpc.unary_unary_rpc_method_handler(
          servicer.BlogsByAll,
          request_deserializer=social3_dot_social3Message__pb2.BlogQueryInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.BlogQueryOutput.SerializeToString,
      ),
      'BlogsByPostType': grpc.unary_unary_rpc_method_handler(
          servicer.BlogsByPostType,
          request_deserializer=social3_dot_social3Message__pb2.BlogsByPostTypeInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.BlogQueryOutput.SerializeToString,
      ),
      'BlogsByBlogType': grpc.unary_unary_rpc_method_handler(
          servicer.BlogsByBlogType,
          request_deserializer=social3_dot_social3Message__pb2.BlogsByBlogTypeInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.BlogQueryOutput.SerializeToString,
      ),
      'CommentAdd': grpc.unary_unary_rpc_method_handler(
          servicer.CommentAdd,
          request_deserializer=social3_dot_social3Message__pb2.CommentAddInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommandOutput.SerializeToString,
      ),
      'CommentsByObject': grpc.unary_unary_rpc_method_handler(
          servicer.CommentsByObject,
          request_deserializer=social3_dot_social3Message__pb2.CommentsByObjectInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommentsByObjectOutput.SerializeToString,
      ),
      'CommentsByUser': grpc.unary_unary_rpc_method_handler(
          servicer.CommentsByUser,
          request_deserializer=social3_dot_social3Message__pb2.CommentsByUserInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommentsByUserOutput.SerializeToString,
      ),
      'CommentDel': grpc.unary_unary_rpc_method_handler(
          servicer.CommentDel,
          request_deserializer=social3_dot_social3Message__pb2.CommentDelInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommandOutput.SerializeToString,
      ),
      'CommentsByManageList': grpc.unary_unary_rpc_method_handler(
          servicer.CommentsByManageList,
          request_deserializer=social3_dot_social3Message__pb2.CommentsByManageListInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommentsByObjectOutput.SerializeToString,
      ),
      'FavoriteAddDel': grpc.unary_unary_rpc_method_handler(
          servicer.FavoriteAddDel,
          request_deserializer=social3_dot_social3Message__pb2.FavoriteAddDelInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommandOutput.SerializeToString,
      ),
      'FavoritesByUser': grpc.unary_unary_rpc_method_handler(
          servicer.FavoritesByUser,
          request_deserializer=social3_dot_social3Message__pb2.FavoritesByUserInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.FavoritesByUserOutput.SerializeToString,
      ),
      'LikesAddDel': grpc.unary_unary_rpc_method_handler(
          servicer.LikesAddDel,
          request_deserializer=social3_dot_social3Message__pb2.LikesAddDelInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommandOutput.SerializeToString,
      ),
      'LikesesByObject': grpc.unary_unary_rpc_method_handler(
          servicer.LikesesByObject,
          request_deserializer=social3_dot_social3Message__pb2.LikesesByObjectInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.LikesesByObjectOutput.SerializeToString,
      ),
      'LikesesByUser': grpc.unary_unary_rpc_method_handler(
          servicer.LikesesByUser,
          request_deserializer=social3_dot_social3Message__pb2.LikesesByUserInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.LikesesByUserOutput.SerializeToString,
      ),
      'AttentionAddDel': grpc.unary_unary_rpc_method_handler(
          servicer.AttentionAddDel,
          request_deserializer=social3_dot_social3Message__pb2.AttentionAddDelInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommandOutput.SerializeToString,
      ),
      'AttentionForce': grpc.unary_unary_rpc_method_handler(
          servicer.AttentionForce,
          request_deserializer=social3_dot_social3Message__pb2.AttentionForceInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommandOutput.SerializeToString,
      ),
      'RelationshipsByUserAttention': grpc.unary_unary_rpc_method_handler(
          servicer.RelationshipsByUserAttention,
          request_deserializer=social3_dot_social3Message__pb2.RelationshipsByUserBaseInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.RelationshipsByUserBaseOutput.SerializeToString,
      ),
      'RelationshipsByUserFans': grpc.unary_unary_rpc_method_handler(
          servicer.RelationshipsByUserFans,
          request_deserializer=social3_dot_social3Message__pb2.RelationshipsByUserBaseInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.RelationshipsByUserBaseOutput.SerializeToString,
      ),
      'RelationshipsByUserToUser': grpc.unary_unary_rpc_method_handler(
          servicer.RelationshipsByUserToUser,
          request_deserializer=social3_dot_social3Message__pb2.RelationshipsByUserToUserInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.RelationshipsByUserToUserOutput.SerializeToString,
      ),
      'RelationshipsByUserToUsers': grpc.unary_unary_rpc_method_handler(
          servicer.RelationshipsByUserToUsers,
          request_deserializer=social3_dot_social3Message__pb2.RelationshipsByUserToUsersInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.RelationshipsByUserToUsersOutput.SerializeToString,
      ),
      'RelationshipsByUserAll': grpc.unary_unary_rpc_method_handler(
          servicer.RelationshipsByUserAll,
          request_deserializer=social3_dot_social3Message__pb2.LongProtoDto.FromString,
          response_serializer=social3_dot_social3Message__pb2.RelationshipsByUserAllOutput.SerializeToString,
      ),
      'StarUsersByUserAttention': grpc.unary_unary_rpc_method_handler(
          servicer.StarUsersByUserAttention,
          request_deserializer=social3_dot_social3Message__pb2.LongProtoDto.FromString,
          response_serializer=social3_dot_social3Message__pb2.StarUsersOutput.SerializeToString,
      ),
      'StarUsersByUserFans': grpc.unary_unary_rpc_method_handler(
          servicer.StarUsersByUserFans,
          request_deserializer=social3_dot_social3Message__pb2.LongProtoDto.FromString,
          response_serializer=social3_dot_social3Message__pb2.StarUsersOutput.SerializeToString,
      ),
      'StarUsersBySystem': grpc.unary_unary_rpc_method_handler(
          servicer.StarUsersBySystem,
          request_deserializer=social3_dot_social3Message__pb2.LongProtoDto.FromString,
          response_serializer=social3_dot_social3Message__pb2.StarUsersOutput.SerializeToString,
      ),
      'HotTopics': grpc.unary_unary_rpc_method_handler(
          servicer.HotTopics,
          request_deserializer=social3_dot_social3Message__pb2.BaseQueryTopicInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.QueryTopicOutput.SerializeToString,
      ),
      'TopicBlogs': grpc.unary_unary_rpc_method_handler(
          servicer.TopicBlogs,
          request_deserializer=social3_dot_social3Message__pb2.BlogQueryInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.BlogQueryOutput.SerializeToString,
      ),
      'UserInfoByUserId': grpc.unary_unary_rpc_method_handler(
          servicer.UserInfoByUserId,
          request_deserializer=social3_dot_social3Message__pb2.LongProtoDto.FromString,
          response_serializer=social3_dot_social3Message__pb2.UserInfoOutput.SerializeToString,
      ),
      'UserSearch': grpc.unary_unary_rpc_method_handler(
          servicer.UserSearch,
          request_deserializer=social3_dot_social3Message__pb2.UserSearchInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.UserSearchOutput.SerializeToString,
      ),
      'UserStatusSet': grpc.unary_unary_rpc_method_handler(
          servicer.UserStatusSet,
          request_deserializer=social3_dot_social3Message__pb2.UserStatusSetInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommandOutput.SerializeToString,
      ),
      'UserStatusGet': grpc.unary_unary_rpc_method_handler(
          servicer.UserStatusGet,
          request_deserializer=social3_dot_social3Message__pb2.UserStatusBaseInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.UserStatusOutput.SerializeToString,
      ),
      'UserStatusClear': grpc.unary_unary_rpc_method_handler(
          servicer.UserStatusClear,
          request_deserializer=social3_dot_social3Message__pb2.UserStatusBaseInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommandOutput.SerializeToString,
      ),
      'AnnouncementsByAll': grpc.unary_unary_rpc_method_handler(
          servicer.AnnouncementsByAll,
          request_deserializer=social3_dot_social3Message__pb2.PageInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.AnnouncementsByAllOutput.SerializeToString,
      ),
      'AnnouncementsByManageList': grpc.unary_unary_rpc_method_handler(
          servicer.AnnouncementsByManageList,
          request_deserializer=social3_dot_social3Message__pb2.AnnouncementsByManageListInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.AnnouncementsByManageListOutput.SerializeToString,
      ),
      'AnnouncementAddUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.AnnouncementAddUpdate,
          request_deserializer=social3_dot_social3Message__pb2.AnnouncementAddUpdateInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommandOutput.SerializeToString,
      ),
      'AnnouncementDel': grpc.unary_unary_rpc_method_handler(
          servicer.AnnouncementDel,
          request_deserializer=social3_dot_social3Message__pb2.AnnouncementDelInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommandOutput.SerializeToString,
      ),
      'RecommendationBlogsByLocation': grpc.unary_unary_rpc_method_handler(
          servicer.RecommendationBlogsByLocation,
          request_deserializer=social3_dot_social3Message__pb2.RecommendationBlogsByLocationInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.RecommendationBlogsByLocationOutput.SerializeToString,
      ),
      'RecommendationAddUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.RecommendationAddUpdate,
          request_deserializer=social3_dot_social3Message__pb2.RecommendationAddUpdateInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommandOutput.SerializeToString,
      ),
      'RecommendationSort': grpc.unary_unary_rpc_method_handler(
          servicer.RecommendationSort,
          request_deserializer=social3_dot_social3Message__pb2.RecommendationSortInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommandOutput.SerializeToString,
      ),
      'RecommendationDel': grpc.unary_unary_rpc_method_handler(
          servicer.RecommendationDel,
          request_deserializer=social3_dot_social3Message__pb2.RecommendationDelInput.FromString,
          response_serializer=social3_dot_social3Message__pb2.CommandOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'social3.SocialService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
