# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
import sys
sys.path.append("../../proto")
from account import account_pb2 as account_dot_account__pb2


class AccountSrvStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ExistAccount = channel.unary_unary(
        '/account.AccountSrv/ExistAccount',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.ExistReply.FromString,
        )
    self.GetUserByAccount = channel.unary_unary(
        '/account.AccountSrv/GetUserByAccount',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.User.FromString,
        )
    self.GetUserById = channel.unary_unary(
        '/account.AccountSrv/GetUserById',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.User.FromString,
        )
    self.SetNickName = channel.unary_unary(
        '/account.AccountSrv/SetNickName',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.SetFavorite = channel.unary_unary(
        '/account.AccountSrv/SetFavorite',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.SetDescription = channel.unary_unary(
        '/account.AccountSrv/SetDescription',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.SetUserDetail = channel.unary_unary(
        '/account.AccountSrv/SetUserDetail',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.ResetPassword = channel.unary_unary(
        '/account.AccountSrv/ResetPassword',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.ResetPasswordAndActivation = channel.unary_unary(
        '/account.AccountSrv/ResetPasswordAndActivation',
        request_serializer=account_dot_account__pb2.ResetPasswordAndActivationRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.Login = channel.unary_unary(
        '/account.AccountSrv/Login',
        request_serializer=account_dot_account__pb2.LoginRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.User.FromString,
        )
    self.GetUserInfo = channel.unary_unary(
        '/account.AccountSrv/GetUserInfo',
        request_serializer=account_dot_account__pb2.LoginRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.UserAndAccount.FromString,
        )
    self.RegisterByEmail = channel.unary_unary(
        '/account.AccountSrv/RegisterByEmail',
        request_serializer=account_dot_account__pb2.RegisterUserRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.User.FromString,
        )
    self.RegisterByMobile = channel.unary_unary(
        '/account.AccountSrv/RegisterByMobile',
        request_serializer=account_dot_account__pb2.RegisterUserRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.User.FromString,
        )
    self.MarketingRegisterByMobile = channel.unary_unary(
        '/account.AccountSrv/MarketingRegisterByMobile',
        request_serializer=account_dot_account__pb2.MarketingRegisterByMobileRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.User.FromString,
        )
    self.RegisterByMobileOrEmail = channel.unary_unary(
        '/account.AccountSrv/RegisterByMobileOrEmail',
        request_serializer=account_dot_account__pb2.RegisterByMobileOrEmailRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.User.FromString,
        )
    self.UpdateUserJoin = channel.unary_unary(
        '/account.AccountSrv/UpdateUserJoin',
        request_serializer=account_dot_account__pb2.UpdateUserJoinRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.UpdateUserInfoAndUserAccount = channel.unary_unary(
        '/account.AccountSrv/UpdateUserInfoAndUserAccount',
        request_serializer=account_dot_account__pb2.UpdateUserInfoAndUserAccountRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.UserAccount.FromString,
        )
    self.SaveUserAccount = channel.unary_unary(
        '/account.AccountSrv/SaveUserAccount',
        request_serializer=account_dot_account__pb2.SaveUserAccountRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.UpdatePassword = channel.unary_unary(
        '/account.AccountSrv/UpdatePassword',
        request_serializer=account_dot_account__pb2.UpdatePasswordRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.UpdatePasswordReply.FromString,
        )
    self.GetShowHelpRecord = channel.unary_unary(
        '/account.AccountSrv/GetShowHelpRecord',
        request_serializer=account_dot_account__pb2.ShowHelpRecord.SerializeToString,
        response_deserializer=account_dot_account__pb2.ShowHelpRecord.FromString,
        )
    self.SaveShowHelpRecord = channel.unary_unary(
        '/account.AccountSrv/SaveShowHelpRecord',
        request_serializer=account_dot_account__pb2.ShowHelpRecord.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.AuditUpgrade = channel.unary_unary(
        '/account.AccountSrv/AuditUpgrade',
        request_serializer=account_dot_account__pb2.AuditUpgradeRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.AuditUpgradeReply.FromString,
        )
    self.GetUpgradeAuditStatus = channel.unary_unary(
        '/account.AccountSrv/GetUpgradeAuditStatus',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.GetUpgradeAuditStatusReply.FromString,
        )
    self.SaveLoginHistory = channel.unary_unary(
        '/account.AccountSrv/SaveLoginHistory',
        request_serializer=account_dot_account__pb2.LoginHistory.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.GetUserList = channel.unary_unary(
        '/account.AccountSrv/GetUserList',
        request_serializer=account_dot_account__pb2.GetUserListRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.GetUserListReply.FromString,
        )
    self.CloseAccount = channel.unary_unary(
        '/account.AccountSrv/CloseAccount',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.GetCachedUserRange = channel.unary_unary(
        '/account.AccountSrv/GetCachedUserRange',
        request_serializer=account_dot_account__pb2.GetUserListRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.GetUserListReply.FromString,
        )
    self.GetCachedUserById = channel.unary_unary(
        '/account.AccountSrv/GetCachedUserById',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.UserAndAccount.FromString,
        )
    self.GetCachedUserByNickName = channel.unary_unary(
        '/account.AccountSrv/GetCachedUserByNickName',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.UserAndAccount.FromString,
        )
    self.GetCachedUserListByNickName = channel.unary_unary(
        '/account.AccountSrv/GetCachedUserListByNickName',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.GetUserListReply.FromString,
        )
    self.GetUserListByRegisterTime = channel.unary_unary(
        '/account.AccountSrv/GetUserListByRegisterTime',
        request_serializer=account_dot_account__pb2.GetUserListRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.GetUserListReply.FromString,
        )
    self.GetUserListByNickName = channel.unary_unary(
        '/account.AccountSrv/GetUserListByNickName',
        request_serializer=account_dot_account__pb2.GetUserListRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.GetUserListReply.FromString,
        )
    self.ReloadCachedUser = channel.unary_unary(
        '/account.AccountSrv/ReloadCachedUser',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.UpdateUserType = channel.unary_unary(
        '/account.AccountSrv/UpdateUserType',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.RegisterFromOA = channel.unary_unary(
        '/account.AccountSrv/RegisterFromOA',
        request_serializer=account_dot_account__pb2.RegisterUserRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.User.FromString,
        )
    self.DisableUser = channel.unary_unary(
        '/account.AccountSrv/DisableUser',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.DeleteUserById = channel.unary_unary(
        '/account.AccountSrv/DeleteUserById',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.UpdateUser = channel.unary_unary(
        '/account.AccountSrv/UpdateUser',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.SendActiveSMS = channel.unary_unary(
        '/account.AccountSrv/SendActiveSMS',
        request_serializer=account_dot_account__pb2.SendSMSRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.SendActiveEmailCode = channel.unary_unary(
        '/account.AccountSrv/SendActiveEmailCode',
        request_serializer=account_dot_account__pb2.SendEmailCodeRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.SendActivationEmail = channel.unary_unary(
        '/account.AccountSrv/SendActivationEmail',
        request_serializer=account_dot_account__pb2.SendActivationEmailRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.GetActivationByObj = channel.unary_unary(
        '/account.AccountSrv/GetActivationByObj',
        request_serializer=account_dot_account__pb2.ActivationRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.Activation.FromString,
        )
    self.GetActivationByActivationCode = channel.unary_unary(
        '/account.AccountSrv/GetActivationByActivationCode',
        request_serializer=account_dot_account__pb2.ActivationRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.Activation.FromString,
        )
    self.SendResetPwdEmail = channel.unary_unary(
        '/account.AccountSrv/SendResetPwdEmail',
        request_serializer=account_dot_account__pb2.SendActivationEmailRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.ValidateEmailLink = channel.unary_unary(
        '/account.AccountSrv/ValidateEmailLink',
        request_serializer=account_dot_account__pb2.ValidateEmailLinkRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.SendUpgradeInvestorEmail = channel.unary_unary(
        '/account.AccountSrv/SendUpgradeInvestorEmail',
        request_serializer=account_dot_account__pb2.UpgradeInvestorEmailRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.SendRegOkEmail = channel.unary_unary(
        '/account.AccountSrv/SendRegOkEmail',
        request_serializer=account_dot_account__pb2.SendActivationEmailRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.SendUpgradeEmail = channel.unary_unary(
        '/account.AccountSrv/SendUpgradeEmail',
        request_serializer=account_dot_account__pb2.UpgradeEmailRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.SendCustomSMS = channel.unary_unary(
        '/account.AccountSrv/SendCustomSMS',
        request_serializer=account_dot_account__pb2.CustomSMSRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.DeleteActivation = channel.unary_unary(
        '/account.AccountSrv/DeleteActivation',
        request_serializer=account_dot_account__pb2.Activation.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.UpdateUserBankInfoByUserId = channel.unary_unary(
        '/account.AccountSrv/UpdateUserBankInfoByUserId',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.UpdateUserDomainInfoByUserId = channel.unary_unary(
        '/account.AccountSrv/UpdateUserDomainInfoByUserId',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.UpdateUserBaseInfoByUserId = channel.unary_unary(
        '/account.AccountSrv/UpdateUserBaseInfoByUserId',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.SaveManagerAccount = channel.unary_unary(
        '/account.AccountSrv/SaveManagerAccount',
        request_serializer=account_dot_account__pb2.SaveManagerAccountRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.HasAssociated = channel.unary_unary(
        '/account.AccountSrv/HasAssociated',
        request_serializer=account_dot_account__pb2.OAuth2User.SerializeToString,
        response_deserializer=account_dot_account__pb2.UserAndAccount.FromString,
        )
    self.LoginBy3RdAccount = channel.unary_unary(
        '/account.AccountSrv/LoginBy3RdAccount',
        request_serializer=account_dot_account__pb2.LoginBy3RdAccountRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.UserAndAccount.FromString,
        )
    self.Associate = channel.unary_unary(
        '/account.AccountSrv/Associate',
        request_serializer=account_dot_account__pb2.OAuth2User.SerializeToString,
        response_deserializer=account_dot_account__pb2.User.FromString,
        )
    self.Bind3RdByNewAccount = channel.unary_unary(
        '/account.AccountSrv/Bind3RdByNewAccount',
        request_serializer=account_dot_account__pb2.Bind3RdAccountRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.User.FromString,
        )
    self.Bind3RdByExistAccount = channel.unary_unary(
        '/account.AccountSrv/Bind3RdByExistAccount',
        request_serializer=account_dot_account__pb2.Bind3RdAccountRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.User.FromString,
        )
    self.GetBind3RdAccountByOpenId = channel.unary_unary(
        '/account.AccountSrv/GetBind3RdAccountByOpenId',
        request_serializer=account_dot_account__pb2.OAuth2User.SerializeToString,
        response_deserializer=account_dot_account__pb2.Bind3RdAccount.FromString,
        )
    self.GetBind3RdAccountByUserId = channel.unary_unary(
        '/account.AccountSrv/GetBind3RdAccountByUserId',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.Bind3RdAccount.FromString,
        )
    self.GetBind3RdAccountListByUserId = channel.unary_unary(
        '/account.AccountSrv/GetBind3RdAccountListByUserId',
        request_serializer=account_dot_account__pb2.User.SerializeToString,
        response_deserializer=account_dot_account__pb2.Bind3RdAccountList.FromString,
        )
    self.SaveTokenAndVcode = channel.unary_unary(
        '/account.AccountSrv/SaveTokenAndVcode',
        request_serializer=account_dot_account__pb2.TokenAndVcode.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.GetVcodeByToken = channel.unary_unary(
        '/account.AccountSrv/GetVcodeByToken',
        request_serializer=account_dot_account__pb2.TokenAndVcode.SerializeToString,
        response_deserializer=account_dot_account__pb2.TokenAndVcode.FromString,
        )
    self.Logout = channel.unary_unary(
        '/account.AccountSrv/Logout',
        request_serializer=account_dot_account__pb2.TokenAndVcode.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.AddActivitySource = channel.unary_unary(
        '/account.AccountSrv/AddActivitySource',
        request_serializer=account_dot_account__pb2.ActivitySource.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.AddOrganization = channel.unary_unary(
        '/account.AccountSrv/AddOrganization',
        request_serializer=account_dot_account__pb2.Organization.SerializeToString,
        response_deserializer=account_dot_account__pb2.Organization.FromString,
        )
    self.GetByOrganizationUserId = channel.unary_unary(
        '/account.AccountSrv/GetByOrganizationUserId',
        request_serializer=account_dot_account__pb2.Organization.SerializeToString,
        response_deserializer=account_dot_account__pb2.Organization.FromString,
        )
    self.GetOrganizationPager = channel.unary_unary(
        '/account.AccountSrv/GetOrganizationPager',
        request_serializer=account_dot_account__pb2.OrganizationPageRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.OrganizationPageReply.FromString,
        )
    self.UpdateOrganization = channel.unary_unary(
        '/account.AccountSrv/UpdateOrganization',
        request_serializer=account_dot_account__pb2.Organization.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.GetOrganizationById = channel.unary_unary(
        '/account.AccountSrv/GetOrganizationById',
        request_serializer=account_dot_account__pb2.Organization.SerializeToString,
        response_deserializer=account_dot_account__pb2.Organization.FromString,
        )
    self.DeleteByOrganizationId = channel.unary_unary(
        '/account.AccountSrv/DeleteByOrganizationId',
        request_serializer=account_dot_account__pb2.Organization.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.GetIdsByOrganizationId = channel.unary_unary(
        '/account.AccountSrv/GetIdsByOrganizationId',
        request_serializer=account_dot_account__pb2.Organization.SerializeToString,
        response_deserializer=account_dot_account__pb2.IdListReply.FromString,
        )
    self.AddOrganizationMember = channel.unary_unary(
        '/account.AccountSrv/AddOrganizationMember',
        request_serializer=account_dot_account__pb2.OrganizationMember.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.GetPartnerUserByToken = channel.unary_unary(
        '/account.AccountSrv/GetPartnerUserByToken',
        request_serializer=account_dot_account__pb2.PartnerUser.SerializeToString,
        response_deserializer=account_dot_account__pb2.PartnerUser.FromString,
        )
    self.GetUpdatedFx168User = channel.unary_unary(
        '/account.AccountSrv/GetUpdatedFx168User',
        request_serializer=account_dot_account__pb2.PartnerUser.SerializeToString,
        response_deserializer=account_dot_account__pb2.PartnerUserListReply.FromString,
        )
    self.UpdateFx168AsyncUser = channel.unary_unary(
        '/account.AccountSrv/UpdateFx168AsyncUser',
        request_serializer=account_dot_account__pb2.PartnerUser.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.SavePartnerUser = channel.unary_unary(
        '/account.AccountSrv/SavePartnerUser',
        request_serializer=account_dot_account__pb2.PartnerUser.SerializeToString,
        response_deserializer=account_dot_account__pb2.PartnerUser.FromString,
        )
    self.GetPersonalCard = channel.unary_unary(
        '/account.AccountSrv/GetPersonalCard',
        request_serializer=account_dot_account__pb2.PersonalCardRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.VPersonalCard.FromString,
        )
    self.CheckExistsAudit = channel.unary_unary(
        '/account.AccountSrv/CheckExistsAudit',
        request_serializer=account_dot_account__pb2.UserAccountAudit.SerializeToString,
        response_deserializer=account_dot_account__pb2.ExistReply.FromString,
        )
    self.GetExistsAudit = channel.unary_unary(
        '/account.AccountSrv/GetExistsAudit',
        request_serializer=account_dot_account__pb2.UserAccountAudit.SerializeToString,
        response_deserializer=account_dot_account__pb2.UserAccountAuditList.FromString,
        )
    self.GetAuditList = channel.unary_unary(
        '/account.AccountSrv/GetAuditList',
        request_serializer=account_dot_account__pb2.FilterRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.UserAccountAuditList.FromString,
        )
    self.GetAuditNum = channel.unary_unary(
        '/account.AccountSrv/GetAuditNum',
        request_serializer=account_dot_account__pb2.UserAccountAudit.SerializeToString,
        response_deserializer=account_dot_account__pb2.CountRequest.FromString,
        )
    self.GetUserAccountAuditList = channel.unary_unary(
        '/account.AccountSrv/GetUserAccountAuditList',
        request_serializer=account_dot_account__pb2.UserAccountAudit.SerializeToString,
        response_deserializer=account_dot_account__pb2.UserAccountAuditList.FromString,
        )
    self.GetOAPointModel = channel.unary_unary(
        '/account.AccountSrv/GetOAPointModel',
        request_serializer=account_dot_account__pb2.UserAccountAudit.SerializeToString,
        response_deserializer=account_dot_account__pb2.UserAccountAudit.FromString,
        )
    self.GetUserAccountAuditById = channel.unary_unary(
        '/account.AccountSrv/GetUserAccountAuditById',
        request_serializer=account_dot_account__pb2.UserAccountAudit.SerializeToString,
        response_deserializer=account_dot_account__pb2.UserAccountAudit.FromString,
        )
    self.UpdateUserAccountAudit = channel.unary_unary(
        '/account.AccountSrv/UpdateUserAccountAudit',
        request_serializer=account_dot_account__pb2.UserAccountAudit.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.AddUserAccountAudit = channel.unary_unary(
        '/account.AccountSrv/AddUserAccountAudit',
        request_serializer=account_dot_account__pb2.UserAccountAudit.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.GetUserAddressByUserId = channel.unary_unary(
        '/account.AccountSrv/GetUserAddressByUserId',
        request_serializer=account_dot_account__pb2.UserAddress.SerializeToString,
        response_deserializer=account_dot_account__pb2.UserAddress.FromString,
        )
    self.GetUserAddressByFilter = channel.unary_unary(
        '/account.AccountSrv/GetUserAddressByFilter',
        request_serializer=account_dot_account__pb2.FilterRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.UserAddress.FromString,
        )
    self.AddUserAddress = channel.unary_unary(
        '/account.AccountSrv/AddUserAddress',
        request_serializer=account_dot_account__pb2.UserAddress.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.UpdateUserAddress = channel.unary_unary(
        '/account.AccountSrv/UpdateUserAddress',
        request_serializer=account_dot_account__pb2.UserAddress.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.GetAreaByAreaCode = channel.unary_unary(
        '/account.AccountSrv/GetAreaByAreaCode',
        request_serializer=account_dot_account__pb2.GetAreaRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.Area.FromString,
        )
    self.GetUserSettingByType = channel.unary_unary(
        '/account.AccountSrv/GetUserSettingByType',
        request_serializer=account_dot_account__pb2.UserSetting.SerializeToString,
        response_deserializer=account_dot_account__pb2.UserSetting.FromString,
        )
    self.AddUserSetting = channel.unary_unary(
        '/account.AccountSrv/AddUserSetting',
        request_serializer=account_dot_account__pb2.UserSetting.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.UpdateUserSetting = channel.unary_unary(
        '/account.AccountSrv/UpdateUserSetting',
        request_serializer=account_dot_account__pb2.UserSetting.SerializeToString,
        response_deserializer=account_dot_account__pb2.SuccessReply.FromString,
        )
    self.PageUser = channel.unary_unary(
        '/account.AccountSrv/PageUser',
        request_serializer=account_dot_account__pb2.PageUserRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.PageUserReply.FromString,
        )
    self.PageUserAndAccount = channel.unary_unary(
        '/account.AccountSrv/PageUserAndAccount',
        request_serializer=account_dot_account__pb2.PageUserRequest.SerializeToString,
        response_deserializer=account_dot_account__pb2.PageUserAndAccountReply.FromString,
        )


class AccountSrvServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ExistAccount(self, request, context):
    """definement from UserBLL
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserByAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetNickName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetFavorite(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetDescription(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetUserDetail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResetPassword(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResetPasswordAndActivation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RegisterByEmail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RegisterByMobile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MarketingRegisterByMobile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RegisterByMobileOrEmail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUserJoin(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUserInfoAndUserAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveUserAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdatePassword(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetShowHelpRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveShowHelpRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AuditUpgrade(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUpgradeAuditStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveLoginHistory(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CloseAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCachedUserRange(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCachedUserById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCachedUserByNickName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCachedUserListByNickName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserListByRegisterTime(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserListByNickName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReloadCachedUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUserType(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RegisterFromOA(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DisableUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteUserById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendActiveSMS(self, request, context):
    """from ActivationBLL
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendActiveEmailCode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendActivationEmail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetActivationByObj(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetActivationByActivationCode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendResetPwdEmail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ValidateEmailLink(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendUpgradeInvestorEmail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendRegOkEmail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendUpgradeEmail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendCustomSMS(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteActivation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUserBankInfoByUserId(self, request, context):
    """for c# member
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUserDomainInfoByUserId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUserBaseInfoByUserId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveManagerAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HasAssociated(self, request, context):
    """from Bind3rdAccountBLL
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LoginBy3RdAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Associate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Bind3RdByNewAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Bind3RdByExistAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBind3RdAccountByOpenId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBind3RdAccountByUserId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBind3RdAccountListByUserId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveTokenAndVcode(self, request, context):
    """for front dev 
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetVcodeByToken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Logout(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddActivitySource(self, request, context):
    """from ActivitySourceBLL
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddOrganization(self, request, context):
    """from OrganizationBLL
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetByOrganizationUserId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetOrganizationPager(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateOrganization(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetOrganizationById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteByOrganizationId(self, request, context):
    """from OrganizationMenber
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetIdsByOrganizationId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddOrganizationMember(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPartnerUserByToken(self, request, context):
    """from PartnerUser
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUpdatedFx168User(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateFx168AsyncUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SavePartnerUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPersonalCard(self, request, context):
    """from PersonalCardBLL
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckExistsAudit(self, request, context):
    """from UserAccountAuditBLL
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetExistsAudit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAuditList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAuditNum(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserAccountAuditList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetOAPointModel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserAccountAuditById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUserAccountAudit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddUserAccountAudit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserAddressByUserId(self, request, context):
    """from UserAddressBLL
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserAddressByFilter(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddUserAddress(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUserAddress(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAreaByAreaCode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserSettingByType(self, request, context):
    """from UserSettingBLL
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddUserSetting(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUserSetting(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PageUser(self, request, context):
    """for oa page User
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PageUserAndAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AccountSrvServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ExistAccount': grpc.unary_unary_rpc_method_handler(
          servicer.ExistAccount,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.ExistReply.SerializeToString,
      ),
      'GetUserByAccount': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserByAccount,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.User.SerializeToString,
      ),
      'GetUserById': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserById,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.User.SerializeToString,
      ),
      'SetNickName': grpc.unary_unary_rpc_method_handler(
          servicer.SetNickName,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'SetFavorite': grpc.unary_unary_rpc_method_handler(
          servicer.SetFavorite,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'SetDescription': grpc.unary_unary_rpc_method_handler(
          servicer.SetDescription,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'SetUserDetail': grpc.unary_unary_rpc_method_handler(
          servicer.SetUserDetail,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'ResetPassword': grpc.unary_unary_rpc_method_handler(
          servicer.ResetPassword,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'ResetPasswordAndActivation': grpc.unary_unary_rpc_method_handler(
          servicer.ResetPasswordAndActivation,
          request_deserializer=account_dot_account__pb2.ResetPasswordAndActivationRequest.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'Login': grpc.unary_unary_rpc_method_handler(
          servicer.Login,
          request_deserializer=account_dot_account__pb2.LoginRequest.FromString,
          response_serializer=account_dot_account__pb2.User.SerializeToString,
      ),
      'GetUserInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserInfo,
          request_deserializer=account_dot_account__pb2.LoginRequest.FromString,
          response_serializer=account_dot_account__pb2.UserAndAccount.SerializeToString,
      ),
      'RegisterByEmail': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterByEmail,
          request_deserializer=account_dot_account__pb2.RegisterUserRequest.FromString,
          response_serializer=account_dot_account__pb2.User.SerializeToString,
      ),
      'RegisterByMobile': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterByMobile,
          request_deserializer=account_dot_account__pb2.RegisterUserRequest.FromString,
          response_serializer=account_dot_account__pb2.User.SerializeToString,
      ),
      'MarketingRegisterByMobile': grpc.unary_unary_rpc_method_handler(
          servicer.MarketingRegisterByMobile,
          request_deserializer=account_dot_account__pb2.MarketingRegisterByMobileRequest.FromString,
          response_serializer=account_dot_account__pb2.User.SerializeToString,
      ),
      'RegisterByMobileOrEmail': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterByMobileOrEmail,
          request_deserializer=account_dot_account__pb2.RegisterByMobileOrEmailRequest.FromString,
          response_serializer=account_dot_account__pb2.User.SerializeToString,
      ),
      'UpdateUserJoin': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUserJoin,
          request_deserializer=account_dot_account__pb2.UpdateUserJoinRequest.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'UpdateUserInfoAndUserAccount': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUserInfoAndUserAccount,
          request_deserializer=account_dot_account__pb2.UpdateUserInfoAndUserAccountRequest.FromString,
          response_serializer=account_dot_account__pb2.UserAccount.SerializeToString,
      ),
      'SaveUserAccount': grpc.unary_unary_rpc_method_handler(
          servicer.SaveUserAccount,
          request_deserializer=account_dot_account__pb2.SaveUserAccountRequest.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'UpdatePassword': grpc.unary_unary_rpc_method_handler(
          servicer.UpdatePassword,
          request_deserializer=account_dot_account__pb2.UpdatePasswordRequest.FromString,
          response_serializer=account_dot_account__pb2.UpdatePasswordReply.SerializeToString,
      ),
      'GetShowHelpRecord': grpc.unary_unary_rpc_method_handler(
          servicer.GetShowHelpRecord,
          request_deserializer=account_dot_account__pb2.ShowHelpRecord.FromString,
          response_serializer=account_dot_account__pb2.ShowHelpRecord.SerializeToString,
      ),
      'SaveShowHelpRecord': grpc.unary_unary_rpc_method_handler(
          servicer.SaveShowHelpRecord,
          request_deserializer=account_dot_account__pb2.ShowHelpRecord.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'AuditUpgrade': grpc.unary_unary_rpc_method_handler(
          servicer.AuditUpgrade,
          request_deserializer=account_dot_account__pb2.AuditUpgradeRequest.FromString,
          response_serializer=account_dot_account__pb2.AuditUpgradeReply.SerializeToString,
      ),
      'GetUpgradeAuditStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetUpgradeAuditStatus,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.GetUpgradeAuditStatusReply.SerializeToString,
      ),
      'SaveLoginHistory': grpc.unary_unary_rpc_method_handler(
          servicer.SaveLoginHistory,
          request_deserializer=account_dot_account__pb2.LoginHistory.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'GetUserList': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserList,
          request_deserializer=account_dot_account__pb2.GetUserListRequest.FromString,
          response_serializer=account_dot_account__pb2.GetUserListReply.SerializeToString,
      ),
      'CloseAccount': grpc.unary_unary_rpc_method_handler(
          servicer.CloseAccount,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'GetCachedUserRange': grpc.unary_unary_rpc_method_handler(
          servicer.GetCachedUserRange,
          request_deserializer=account_dot_account__pb2.GetUserListRequest.FromString,
          response_serializer=account_dot_account__pb2.GetUserListReply.SerializeToString,
      ),
      'GetCachedUserById': grpc.unary_unary_rpc_method_handler(
          servicer.GetCachedUserById,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.UserAndAccount.SerializeToString,
      ),
      'GetCachedUserByNickName': grpc.unary_unary_rpc_method_handler(
          servicer.GetCachedUserByNickName,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.UserAndAccount.SerializeToString,
      ),
      'GetCachedUserListByNickName': grpc.unary_unary_rpc_method_handler(
          servicer.GetCachedUserListByNickName,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.GetUserListReply.SerializeToString,
      ),
      'GetUserListByRegisterTime': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserListByRegisterTime,
          request_deserializer=account_dot_account__pb2.GetUserListRequest.FromString,
          response_serializer=account_dot_account__pb2.GetUserListReply.SerializeToString,
      ),
      'GetUserListByNickName': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserListByNickName,
          request_deserializer=account_dot_account__pb2.GetUserListRequest.FromString,
          response_serializer=account_dot_account__pb2.GetUserListReply.SerializeToString,
      ),
      'ReloadCachedUser': grpc.unary_unary_rpc_method_handler(
          servicer.ReloadCachedUser,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'UpdateUserType': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUserType,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'RegisterFromOA': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterFromOA,
          request_deserializer=account_dot_account__pb2.RegisterUserRequest.FromString,
          response_serializer=account_dot_account__pb2.User.SerializeToString,
      ),
      'DisableUser': grpc.unary_unary_rpc_method_handler(
          servicer.DisableUser,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'DeleteUserById': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteUserById,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'UpdateUser': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUser,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'SendActiveSMS': grpc.unary_unary_rpc_method_handler(
          servicer.SendActiveSMS,
          request_deserializer=account_dot_account__pb2.SendSMSRequest.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'SendActiveEmailCode': grpc.unary_unary_rpc_method_handler(
          servicer.SendActiveEmailCode,
          request_deserializer=account_dot_account__pb2.SendEmailCodeRequest.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'SendActivationEmail': grpc.unary_unary_rpc_method_handler(
          servicer.SendActivationEmail,
          request_deserializer=account_dot_account__pb2.SendActivationEmailRequest.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'GetActivationByObj': grpc.unary_unary_rpc_method_handler(
          servicer.GetActivationByObj,
          request_deserializer=account_dot_account__pb2.ActivationRequest.FromString,
          response_serializer=account_dot_account__pb2.Activation.SerializeToString,
      ),
      'GetActivationByActivationCode': grpc.unary_unary_rpc_method_handler(
          servicer.GetActivationByActivationCode,
          request_deserializer=account_dot_account__pb2.ActivationRequest.FromString,
          response_serializer=account_dot_account__pb2.Activation.SerializeToString,
      ),
      'SendResetPwdEmail': grpc.unary_unary_rpc_method_handler(
          servicer.SendResetPwdEmail,
          request_deserializer=account_dot_account__pb2.SendActivationEmailRequest.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'ValidateEmailLink': grpc.unary_unary_rpc_method_handler(
          servicer.ValidateEmailLink,
          request_deserializer=account_dot_account__pb2.ValidateEmailLinkRequest.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'SendUpgradeInvestorEmail': grpc.unary_unary_rpc_method_handler(
          servicer.SendUpgradeInvestorEmail,
          request_deserializer=account_dot_account__pb2.UpgradeInvestorEmailRequest.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'SendRegOkEmail': grpc.unary_unary_rpc_method_handler(
          servicer.SendRegOkEmail,
          request_deserializer=account_dot_account__pb2.SendActivationEmailRequest.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'SendUpgradeEmail': grpc.unary_unary_rpc_method_handler(
          servicer.SendUpgradeEmail,
          request_deserializer=account_dot_account__pb2.UpgradeEmailRequest.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'SendCustomSMS': grpc.unary_unary_rpc_method_handler(
          servicer.SendCustomSMS,
          request_deserializer=account_dot_account__pb2.CustomSMSRequest.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'DeleteActivation': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteActivation,
          request_deserializer=account_dot_account__pb2.Activation.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'UpdateUserBankInfoByUserId': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUserBankInfoByUserId,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'UpdateUserDomainInfoByUserId': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUserDomainInfoByUserId,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'UpdateUserBaseInfoByUserId': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUserBaseInfoByUserId,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'SaveManagerAccount': grpc.unary_unary_rpc_method_handler(
          servicer.SaveManagerAccount,
          request_deserializer=account_dot_account__pb2.SaveManagerAccountRequest.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'HasAssociated': grpc.unary_unary_rpc_method_handler(
          servicer.HasAssociated,
          request_deserializer=account_dot_account__pb2.OAuth2User.FromString,
          response_serializer=account_dot_account__pb2.UserAndAccount.SerializeToString,
      ),
      'LoginBy3RdAccount': grpc.unary_unary_rpc_method_handler(
          servicer.LoginBy3RdAccount,
          request_deserializer=account_dot_account__pb2.LoginBy3RdAccountRequest.FromString,
          response_serializer=account_dot_account__pb2.UserAndAccount.SerializeToString,
      ),
      'Associate': grpc.unary_unary_rpc_method_handler(
          servicer.Associate,
          request_deserializer=account_dot_account__pb2.OAuth2User.FromString,
          response_serializer=account_dot_account__pb2.User.SerializeToString,
      ),
      'Bind3RdByNewAccount': grpc.unary_unary_rpc_method_handler(
          servicer.Bind3RdByNewAccount,
          request_deserializer=account_dot_account__pb2.Bind3RdAccountRequest.FromString,
          response_serializer=account_dot_account__pb2.User.SerializeToString,
      ),
      'Bind3RdByExistAccount': grpc.unary_unary_rpc_method_handler(
          servicer.Bind3RdByExistAccount,
          request_deserializer=account_dot_account__pb2.Bind3RdAccountRequest.FromString,
          response_serializer=account_dot_account__pb2.User.SerializeToString,
      ),
      'GetBind3RdAccountByOpenId': grpc.unary_unary_rpc_method_handler(
          servicer.GetBind3RdAccountByOpenId,
          request_deserializer=account_dot_account__pb2.OAuth2User.FromString,
          response_serializer=account_dot_account__pb2.Bind3RdAccount.SerializeToString,
      ),
      'GetBind3RdAccountByUserId': grpc.unary_unary_rpc_method_handler(
          servicer.GetBind3RdAccountByUserId,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.Bind3RdAccount.SerializeToString,
      ),
      'GetBind3RdAccountListByUserId': grpc.unary_unary_rpc_method_handler(
          servicer.GetBind3RdAccountListByUserId,
          request_deserializer=account_dot_account__pb2.User.FromString,
          response_serializer=account_dot_account__pb2.Bind3RdAccountList.SerializeToString,
      ),
      'SaveTokenAndVcode': grpc.unary_unary_rpc_method_handler(
          servicer.SaveTokenAndVcode,
          request_deserializer=account_dot_account__pb2.TokenAndVcode.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'GetVcodeByToken': grpc.unary_unary_rpc_method_handler(
          servicer.GetVcodeByToken,
          request_deserializer=account_dot_account__pb2.TokenAndVcode.FromString,
          response_serializer=account_dot_account__pb2.TokenAndVcode.SerializeToString,
      ),
      'Logout': grpc.unary_unary_rpc_method_handler(
          servicer.Logout,
          request_deserializer=account_dot_account__pb2.TokenAndVcode.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'AddActivitySource': grpc.unary_unary_rpc_method_handler(
          servicer.AddActivitySource,
          request_deserializer=account_dot_account__pb2.ActivitySource.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'AddOrganization': grpc.unary_unary_rpc_method_handler(
          servicer.AddOrganization,
          request_deserializer=account_dot_account__pb2.Organization.FromString,
          response_serializer=account_dot_account__pb2.Organization.SerializeToString,
      ),
      'GetByOrganizationUserId': grpc.unary_unary_rpc_method_handler(
          servicer.GetByOrganizationUserId,
          request_deserializer=account_dot_account__pb2.Organization.FromString,
          response_serializer=account_dot_account__pb2.Organization.SerializeToString,
      ),
      'GetOrganizationPager': grpc.unary_unary_rpc_method_handler(
          servicer.GetOrganizationPager,
          request_deserializer=account_dot_account__pb2.OrganizationPageRequest.FromString,
          response_serializer=account_dot_account__pb2.OrganizationPageReply.SerializeToString,
      ),
      'UpdateOrganization': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateOrganization,
          request_deserializer=account_dot_account__pb2.Organization.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'GetOrganizationById': grpc.unary_unary_rpc_method_handler(
          servicer.GetOrganizationById,
          request_deserializer=account_dot_account__pb2.Organization.FromString,
          response_serializer=account_dot_account__pb2.Organization.SerializeToString,
      ),
      'DeleteByOrganizationId': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteByOrganizationId,
          request_deserializer=account_dot_account__pb2.Organization.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'GetIdsByOrganizationId': grpc.unary_unary_rpc_method_handler(
          servicer.GetIdsByOrganizationId,
          request_deserializer=account_dot_account__pb2.Organization.FromString,
          response_serializer=account_dot_account__pb2.IdListReply.SerializeToString,
      ),
      'AddOrganizationMember': grpc.unary_unary_rpc_method_handler(
          servicer.AddOrganizationMember,
          request_deserializer=account_dot_account__pb2.OrganizationMember.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'GetPartnerUserByToken': grpc.unary_unary_rpc_method_handler(
          servicer.GetPartnerUserByToken,
          request_deserializer=account_dot_account__pb2.PartnerUser.FromString,
          response_serializer=account_dot_account__pb2.PartnerUser.SerializeToString,
      ),
      'GetUpdatedFx168User': grpc.unary_unary_rpc_method_handler(
          servicer.GetUpdatedFx168User,
          request_deserializer=account_dot_account__pb2.PartnerUser.FromString,
          response_serializer=account_dot_account__pb2.PartnerUserListReply.SerializeToString,
      ),
      'UpdateFx168AsyncUser': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateFx168AsyncUser,
          request_deserializer=account_dot_account__pb2.PartnerUser.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'SavePartnerUser': grpc.unary_unary_rpc_method_handler(
          servicer.SavePartnerUser,
          request_deserializer=account_dot_account__pb2.PartnerUser.FromString,
          response_serializer=account_dot_account__pb2.PartnerUser.SerializeToString,
      ),
      'GetPersonalCard': grpc.unary_unary_rpc_method_handler(
          servicer.GetPersonalCard,
          request_deserializer=account_dot_account__pb2.PersonalCardRequest.FromString,
          response_serializer=account_dot_account__pb2.VPersonalCard.SerializeToString,
      ),
      'CheckExistsAudit': grpc.unary_unary_rpc_method_handler(
          servicer.CheckExistsAudit,
          request_deserializer=account_dot_account__pb2.UserAccountAudit.FromString,
          response_serializer=account_dot_account__pb2.ExistReply.SerializeToString,
      ),
      'GetExistsAudit': grpc.unary_unary_rpc_method_handler(
          servicer.GetExistsAudit,
          request_deserializer=account_dot_account__pb2.UserAccountAudit.FromString,
          response_serializer=account_dot_account__pb2.UserAccountAuditList.SerializeToString,
      ),
      'GetAuditList': grpc.unary_unary_rpc_method_handler(
          servicer.GetAuditList,
          request_deserializer=account_dot_account__pb2.FilterRequest.FromString,
          response_serializer=account_dot_account__pb2.UserAccountAuditList.SerializeToString,
      ),
      'GetAuditNum': grpc.unary_unary_rpc_method_handler(
          servicer.GetAuditNum,
          request_deserializer=account_dot_account__pb2.UserAccountAudit.FromString,
          response_serializer=account_dot_account__pb2.CountRequest.SerializeToString,
      ),
      'GetUserAccountAuditList': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserAccountAuditList,
          request_deserializer=account_dot_account__pb2.UserAccountAudit.FromString,
          response_serializer=account_dot_account__pb2.UserAccountAuditList.SerializeToString,
      ),
      'GetOAPointModel': grpc.unary_unary_rpc_method_handler(
          servicer.GetOAPointModel,
          request_deserializer=account_dot_account__pb2.UserAccountAudit.FromString,
          response_serializer=account_dot_account__pb2.UserAccountAudit.SerializeToString,
      ),
      'GetUserAccountAuditById': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserAccountAuditById,
          request_deserializer=account_dot_account__pb2.UserAccountAudit.FromString,
          response_serializer=account_dot_account__pb2.UserAccountAudit.SerializeToString,
      ),
      'UpdateUserAccountAudit': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUserAccountAudit,
          request_deserializer=account_dot_account__pb2.UserAccountAudit.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'AddUserAccountAudit': grpc.unary_unary_rpc_method_handler(
          servicer.AddUserAccountAudit,
          request_deserializer=account_dot_account__pb2.UserAccountAudit.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'GetUserAddressByUserId': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserAddressByUserId,
          request_deserializer=account_dot_account__pb2.UserAddress.FromString,
          response_serializer=account_dot_account__pb2.UserAddress.SerializeToString,
      ),
      'GetUserAddressByFilter': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserAddressByFilter,
          request_deserializer=account_dot_account__pb2.FilterRequest.FromString,
          response_serializer=account_dot_account__pb2.UserAddress.SerializeToString,
      ),
      'AddUserAddress': grpc.unary_unary_rpc_method_handler(
          servicer.AddUserAddress,
          request_deserializer=account_dot_account__pb2.UserAddress.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'UpdateUserAddress': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUserAddress,
          request_deserializer=account_dot_account__pb2.UserAddress.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'GetAreaByAreaCode': grpc.unary_unary_rpc_method_handler(
          servicer.GetAreaByAreaCode,
          request_deserializer=account_dot_account__pb2.GetAreaRequest.FromString,
          response_serializer=account_dot_account__pb2.Area.SerializeToString,
      ),
      'GetUserSettingByType': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserSettingByType,
          request_deserializer=account_dot_account__pb2.UserSetting.FromString,
          response_serializer=account_dot_account__pb2.UserSetting.SerializeToString,
      ),
      'AddUserSetting': grpc.unary_unary_rpc_method_handler(
          servicer.AddUserSetting,
          request_deserializer=account_dot_account__pb2.UserSetting.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'UpdateUserSetting': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUserSetting,
          request_deserializer=account_dot_account__pb2.UserSetting.FromString,
          response_serializer=account_dot_account__pb2.SuccessReply.SerializeToString,
      ),
      'PageUser': grpc.unary_unary_rpc_method_handler(
          servicer.PageUser,
          request_deserializer=account_dot_account__pb2.PageUserRequest.FromString,
          response_serializer=account_dot_account__pb2.PageUserReply.SerializeToString,
      ),
      'PageUserAndAccount': grpc.unary_unary_rpc_method_handler(
          servicer.PageUserAndAccount,
          request_deserializer=account_dot_account__pb2.PageUserRequest.FromString,
          response_serializer=account_dot_account__pb2.PageUserAndAccountReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'account.AccountSrv', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
