# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
import sys
sys.path.append("../../proto")
from copytrade import copytrade_pb2 as copytrade_dot_copytrade__pb2


class CopyTradeSrvStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateDemoAccount = channel.unary_unary(
        '/copytrade.CopyTradeSrv/CreateDemoAccount',
        request_serializer=copytrade_dot_copytrade__pb2.Account.SerializeToString,
        response_deserializer=copytrade_dot_copytrade__pb2.Account.FromString,
        )
    self.CheckAccount = channel.unary_unary(
        '/copytrade.CopyTradeSrv/CheckAccount',
        request_serializer=copytrade_dot_copytrade__pb2.AccountInfo.SerializeToString,
        response_deserializer=copytrade_dot_copytrade__pb2.AccountInfo.FromString,
        )
    self.Follow = channel.unary_unary(
        '/copytrade.CopyTradeSrv/Follow',
        request_serializer=copytrade_dot_copytrade__pb2.FollowInfo.SerializeToString,
        response_deserializer=copytrade_dot_copytrade__pb2.FollowInfo.FromString,
        )
    self.Unfollow = channel.unary_unary(
        '/copytrade.CopyTradeSrv/Unfollow',
        request_serializer=copytrade_dot_copytrade__pb2.FollowInfo.SerializeToString,
        response_deserializer=copytrade_dot_copytrade__pb2.FollowInfo.FromString,
        )
    self.JoinTrader = channel.unary_unary(
        '/copytrade.CopyTradeSrv/JoinTrader',
        request_serializer=copytrade_dot_copytrade__pb2.Trader.SerializeToString,
        response_deserializer=copytrade_dot_copytrade__pb2.Trader.FromString,
        )
    self.SaveSymbol = channel.unary_unary(
        '/copytrade.CopyTradeSrv/SaveSymbol',
        request_serializer=copytrade_dot_copytrade__pb2.Symbol.SerializeToString,
        response_deserializer=copytrade_dot_copytrade__pb2.Symbol.FromString,
        )
    self.SaveBrokerSymbol = channel.unary_unary(
        '/copytrade.CopyTradeSrv/SaveBrokerSymbol',
        request_serializer=copytrade_dot_copytrade__pb2.BrokerSymbol.SerializeToString,
        response_deserializer=copytrade_dot_copytrade__pb2.BrokerSymbol.FromString,
        )
    self.DeleteBrokerSymbol = channel.unary_unary(
        '/copytrade.CopyTradeSrv/DeleteBrokerSymbol',
        request_serializer=copytrade_dot_copytrade__pb2.BrokerSymbol.SerializeToString,
        response_deserializer=copytrade_dot_copytrade__pb2.Empty.FromString,
        )
    self.GetFollowOrder = channel.unary_unary(
        '/copytrade.CopyTradeSrv/GetFollowOrder',
        request_serializer=copytrade_dot_copytrade__pb2.FollowOrder.SerializeToString,
        response_deserializer=copytrade_dot_copytrade__pb2.FollowOrder.FromString,
        )
    self.UnbindFollowOrder = channel.unary_unary(
        '/copytrade.CopyTradeSrv/UnbindFollowOrder',
        request_serializer=copytrade_dot_copytrade__pb2.FollowOrder.SerializeToString,
        response_deserializer=copytrade_dot_copytrade__pb2.Empty.FromString,
        )
    self.AddBroker = channel.unary_unary(
        '/copytrade.CopyTradeSrv/AddBroker',
        request_serializer=copytrade_dot_copytrade__pb2.Broker.SerializeToString,
        response_deserializer=copytrade_dot_copytrade__pb2.Broker.FromString,
        )
    self.UpdateBroker = channel.unary_unary(
        '/copytrade.CopyTradeSrv/UpdateBroker',
        request_serializer=copytrade_dot_copytrade__pb2.Broker.SerializeToString,
        response_deserializer=copytrade_dot_copytrade__pb2.Broker.FromString,
        )


class CopyTradeSrvServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateDemoAccount(self, request, context):
    """新建模拟账号
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckAccount(self, request, context):
    """校验账户
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Follow(self, request, context):
    """增加跟随关系
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Unfollow(self, request, context):
    """解除跟随关系
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def JoinTrader(self, request, context):
    """加入交易员
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveSymbol(self, request, context):
    """保存交易品种
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveBrokerSymbol(self, request, context):
    """保存经纪商交易品种
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteBrokerSymbol(self, request, context):
    """根据id删除经纪商交易品种
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFollowOrder(self, request, context):
    """获取followorder
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UnbindFollowOrder(self, request, context):
    """解绑订单
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddBroker(self, request, context):
    """增加经纪商
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateBroker(self, request, context):
    """更新经纪商
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CopyTradeSrvServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateDemoAccount': grpc.unary_unary_rpc_method_handler(
          servicer.CreateDemoAccount,
          request_deserializer=copytrade_dot_copytrade__pb2.Account.FromString,
          response_serializer=copytrade_dot_copytrade__pb2.Account.SerializeToString,
      ),
      'CheckAccount': grpc.unary_unary_rpc_method_handler(
          servicer.CheckAccount,
          request_deserializer=copytrade_dot_copytrade__pb2.AccountInfo.FromString,
          response_serializer=copytrade_dot_copytrade__pb2.AccountInfo.SerializeToString,
      ),
      'Follow': grpc.unary_unary_rpc_method_handler(
          servicer.Follow,
          request_deserializer=copytrade_dot_copytrade__pb2.FollowInfo.FromString,
          response_serializer=copytrade_dot_copytrade__pb2.FollowInfo.SerializeToString,
      ),
      'Unfollow': grpc.unary_unary_rpc_method_handler(
          servicer.Unfollow,
          request_deserializer=copytrade_dot_copytrade__pb2.FollowInfo.FromString,
          response_serializer=copytrade_dot_copytrade__pb2.FollowInfo.SerializeToString,
      ),
      'JoinTrader': grpc.unary_unary_rpc_method_handler(
          servicer.JoinTrader,
          request_deserializer=copytrade_dot_copytrade__pb2.Trader.FromString,
          response_serializer=copytrade_dot_copytrade__pb2.Trader.SerializeToString,
      ),
      'SaveSymbol': grpc.unary_unary_rpc_method_handler(
          servicer.SaveSymbol,
          request_deserializer=copytrade_dot_copytrade__pb2.Symbol.FromString,
          response_serializer=copytrade_dot_copytrade__pb2.Symbol.SerializeToString,
      ),
      'SaveBrokerSymbol': grpc.unary_unary_rpc_method_handler(
          servicer.SaveBrokerSymbol,
          request_deserializer=copytrade_dot_copytrade__pb2.BrokerSymbol.FromString,
          response_serializer=copytrade_dot_copytrade__pb2.BrokerSymbol.SerializeToString,
      ),
      'DeleteBrokerSymbol': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteBrokerSymbol,
          request_deserializer=copytrade_dot_copytrade__pb2.BrokerSymbol.FromString,
          response_serializer=copytrade_dot_copytrade__pb2.Empty.SerializeToString,
      ),
      'GetFollowOrder': grpc.unary_unary_rpc_method_handler(
          servicer.GetFollowOrder,
          request_deserializer=copytrade_dot_copytrade__pb2.FollowOrder.FromString,
          response_serializer=copytrade_dot_copytrade__pb2.FollowOrder.SerializeToString,
      ),
      'UnbindFollowOrder': grpc.unary_unary_rpc_method_handler(
          servicer.UnbindFollowOrder,
          request_deserializer=copytrade_dot_copytrade__pb2.FollowOrder.FromString,
          response_serializer=copytrade_dot_copytrade__pb2.Empty.SerializeToString,
      ),
      'AddBroker': grpc.unary_unary_rpc_method_handler(
          servicer.AddBroker,
          request_deserializer=copytrade_dot_copytrade__pb2.Broker.FromString,
          response_serializer=copytrade_dot_copytrade__pb2.Broker.SerializeToString,
      ),
      'UpdateBroker': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateBroker,
          request_deserializer=copytrade_dot_copytrade__pb2.Broker.FromString,
          response_serializer=copytrade_dot_copytrade__pb2.Broker.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'copytrade.CopyTradeSrv', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
