# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sms/sms.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sms/sms.proto',
  package='sms',
  syntax='proto3',
  serialized_pb=_b('\n\rsms/sms.proto\x12\x03sms\"g\n\x15SendVerifyCodeRequest\x12\x12\n\nnationcode\x18\x01 \x01(\t\x12\x13\n\x0bphoneNumber\x18\x02 \x01(\t\x12\x12\n\nverifycode\x18\x03 \x01(\t\x12\x11\n\ttemplteId\x18\x04 \x01(\x05\"\xbf\x01\n\x0bSendRequest\x12\x14\n\x0cPhoneNumbers\x18\x02 \x01(\t\x12\x0f\n\x07\x43ontent\x18\x03 \x01(\t\x12\x0b\n\x03\x45xt\x18\x04 \x01(\t\x12\x10\n\x08SendTime\x18\x05 \x01(\t\x12\x0c\n\x04RRID\x18\x06 \x01(\t\x12\x1b\n\x06SMSISP\x18\x07 \x01(\x0e\x32\x0b.sms.SMSISP\x12\x12\n\nTemplateId\x18\x08 \x01(\x05\x12+\n\x0eNeteaseSMSType\x18\t \x01(\x0e\x32\x13.sms.NeteaseSMSType\"5\n\x0cSendResponse\x12\x0f\n\x07Success\x18\x01 \x01(\x08\x12\x14\n\x0c\x45rrorMessage\x18\x02 \x01(\t*$\n\x06SMSISP\x12\r\n\tFunctions\x10\x00\x12\x0b\n\x07Netease\x10\x01*(\n\x0eNeteaseSMSType\x12\x0c\n\x08Template\x10\x00\x12\x08\n\x04\x43ODE\x10\x01\x32\xc5\x01\n\x06SmsSrv\x12-\n\x04Send\x12\x10.sms.SendRequest\x1a\x11.sms.SendResponse\"\x00\x12\x46\n\x13SendVoiceVerifyCode\x12\x1a.sms.SendVerifyCodeRequest\x1a\x11.sms.SendResponse\"\x00\x12\x44\n\x11SendSmsVerifyCode\x12\x1a.sms.SendVerifyCodeRequest\x1a\x11.sms.SendResponse\"\x00\x42\t\xaa\x02\x06\x46M.SMSb\x06proto3')
)

_SMSISP = _descriptor.EnumDescriptor(
  name='SMSISP',
  full_name='sms.SMSISP',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Functions', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Netease', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=376,
  serialized_end=412,
)
_sym_db.RegisterEnumDescriptor(_SMSISP)

SMSISP = enum_type_wrapper.EnumTypeWrapper(_SMSISP)
_NETEASESMSTYPE = _descriptor.EnumDescriptor(
  name='NeteaseSMSType',
  full_name='sms.NeteaseSMSType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Template', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CODE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=414,
  serialized_end=454,
)
_sym_db.RegisterEnumDescriptor(_NETEASESMSTYPE)

NeteaseSMSType = enum_type_wrapper.EnumTypeWrapper(_NETEASESMSTYPE)
Functions = 0
Netease = 1
Template = 0
CODE = 1



_SENDVERIFYCODEREQUEST = _descriptor.Descriptor(
  name='SendVerifyCodeRequest',
  full_name='sms.SendVerifyCodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nationcode', full_name='sms.SendVerifyCodeRequest.nationcode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phoneNumber', full_name='sms.SendVerifyCodeRequest.phoneNumber', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='verifycode', full_name='sms.SendVerifyCodeRequest.verifycode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='templteId', full_name='sms.SendVerifyCodeRequest.templteId', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=125,
)


_SENDREQUEST = _descriptor.Descriptor(
  name='SendRequest',
  full_name='sms.SendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PhoneNumbers', full_name='sms.SendRequest.PhoneNumbers', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Content', full_name='sms.SendRequest.Content', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Ext', full_name='sms.SendRequest.Ext', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SendTime', full_name='sms.SendRequest.SendTime', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RRID', full_name='sms.SendRequest.RRID', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SMSISP', full_name='sms.SendRequest.SMSISP', index=5,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TemplateId', full_name='sms.SendRequest.TemplateId', index=6,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NeteaseSMSType', full_name='sms.SendRequest.NeteaseSMSType', index=7,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=319,
)


_SENDRESPONSE = _descriptor.Descriptor(
  name='SendResponse',
  full_name='sms.SendResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Success', full_name='sms.SendResponse.Success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ErrorMessage', full_name='sms.SendResponse.ErrorMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=374,
)

_SENDREQUEST.fields_by_name['SMSISP'].enum_type = _SMSISP
_SENDREQUEST.fields_by_name['NeteaseSMSType'].enum_type = _NETEASESMSTYPE
DESCRIPTOR.message_types_by_name['SendVerifyCodeRequest'] = _SENDVERIFYCODEREQUEST
DESCRIPTOR.message_types_by_name['SendRequest'] = _SENDREQUEST
DESCRIPTOR.message_types_by_name['SendResponse'] = _SENDRESPONSE
DESCRIPTOR.enum_types_by_name['SMSISP'] = _SMSISP
DESCRIPTOR.enum_types_by_name['NeteaseSMSType'] = _NETEASESMSTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendVerifyCodeRequest = _reflection.GeneratedProtocolMessageType('SendVerifyCodeRequest', (_message.Message,), dict(
  DESCRIPTOR = _SENDVERIFYCODEREQUEST,
  __module__ = 'sms.sms_pb2'
  # @@protoc_insertion_point(class_scope:sms.SendVerifyCodeRequest)
  ))
_sym_db.RegisterMessage(SendVerifyCodeRequest)

SendRequest = _reflection.GeneratedProtocolMessageType('SendRequest', (_message.Message,), dict(
  DESCRIPTOR = _SENDREQUEST,
  __module__ = 'sms.sms_pb2'
  # @@protoc_insertion_point(class_scope:sms.SendRequest)
  ))
_sym_db.RegisterMessage(SendRequest)

SendResponse = _reflection.GeneratedProtocolMessageType('SendResponse', (_message.Message,), dict(
  DESCRIPTOR = _SENDRESPONSE,
  __module__ = 'sms.sms_pb2'
  # @@protoc_insertion_point(class_scope:sms.SendResponse)
  ))
_sym_db.RegisterMessage(SendResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\006FM.SMS'))

_SMSSRV = _descriptor.ServiceDescriptor(
  name='SmsSrv',
  full_name='sms.SmsSrv',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=457,
  serialized_end=654,
  methods=[
  _descriptor.MethodDescriptor(
    name='Send',
    full_name='sms.SmsSrv.Send',
    index=0,
    containing_service=None,
    input_type=_SENDREQUEST,
    output_type=_SENDRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendVoiceVerifyCode',
    full_name='sms.SmsSrv.SendVoiceVerifyCode',
    index=1,
    containing_service=None,
    input_type=_SENDVERIFYCODEREQUEST,
    output_type=_SENDRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendSmsVerifyCode',
    full_name='sms.SmsSrv.SendSmsVerifyCode',
    index=2,
    containing_service=None,
    input_type=_SENDVERIFYCODEREQUEST,
    output_type=_SENDRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SMSSRV)

DESCRIPTOR.services_by_name['SmsSrv'] = _SMSSRV

# @@protoc_insertion_point(module_scope)
