# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from sms import sms_pb2 as sms_dot_sms__pb2


class SmsSrvStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Send = channel.unary_unary(
        '/sms.SmsSrv/Send',
        request_serializer=sms_dot_sms__pb2.SendRequest.SerializeToString,
        response_deserializer=sms_dot_sms__pb2.SendResponse.FromString,
        )
    self.SendVoiceVerifyCode = channel.unary_unary(
        '/sms.SmsSrv/SendVoiceVerifyCode',
        request_serializer=sms_dot_sms__pb2.SendVerifyCodeRequest.SerializeToString,
        response_deserializer=sms_dot_sms__pb2.SendResponse.FromString,
        )
    self.SendSmsVerifyCode = channel.unary_unary(
        '/sms.SmsSrv/SendSmsVerifyCode',
        request_serializer=sms_dot_sms__pb2.SendVerifyCodeRequest.SerializeToString,
        response_deserializer=sms_dot_sms__pb2.SendResponse.FromString,
        )


class SmsSrvServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Send(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendVoiceVerifyCode(self, request, context):
    """语音验证码
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendSmsVerifyCode(self, request, context):
    """短信验证码
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SmsSrvServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Send': grpc.unary_unary_rpc_method_handler(
          servicer.Send,
          request_deserializer=sms_dot_sms__pb2.SendRequest.FromString,
          response_serializer=sms_dot_sms__pb2.SendResponse.SerializeToString,
      ),
      'SendVoiceVerifyCode': grpc.unary_unary_rpc_method_handler(
          servicer.SendVoiceVerifyCode,
          request_deserializer=sms_dot_sms__pb2.SendVerifyCodeRequest.FromString,
          response_serializer=sms_dot_sms__pb2.SendResponse.SerializeToString,
      ),
      'SendSmsVerifyCode': grpc.unary_unary_rpc_method_handler(
          servicer.SendSmsVerifyCode,
          request_deserializer=sms_dot_sms__pb2.SendVerifyCodeRequest.FromString,
          response_serializer=sms_dot_sms__pb2.SendResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sms.SmsSrv', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
