# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: page/page.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='page/page.proto',
  package='page',
  syntax='proto3',
  serialized_pb=_b('\n\x0fpage/page.proto\x12\x04page\"\x0b\n\tTimeRange\"[\n\nPageOption\x12\x0c\n\x04Page\x18\x01 \x01(\x05\x12\x10\n\x08PageSize\x18\x02 \x01(\x05\x12\r\n\x05\x43ount\x18\x03 \x01(\x08\x12\x0f\n\x07StartAt\x18\n \x01(\x03\x12\r\n\x05\x45ndAt\x18\x0b \x01(\x03\x42\x18\xaa\x02\x15\x43sharpRPCLibrary.Grpcb\x06proto3')
)




_TIMERANGE = _descriptor.Descriptor(
  name='TimeRange',
  full_name='page.TimeRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=36,
)


_PAGEOPTION = _descriptor.Descriptor(
  name='PageOption',
  full_name='page.PageOption',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Page', full_name='page.PageOption.Page', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PageSize', full_name='page.PageOption.PageSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Count', full_name='page.PageOption.Count', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='StartAt', full_name='page.PageOption.StartAt', index=3,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='EndAt', full_name='page.PageOption.EndAt', index=4,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['TimeRange'] = _TIMERANGE
DESCRIPTOR.message_types_by_name['PageOption'] = _PAGEOPTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeRange = _reflection.GeneratedProtocolMessageType('TimeRange', (_message.Message,), dict(
  DESCRIPTOR = _TIMERANGE,
  __module__ = 'page.page_pb2'
  # @@protoc_insertion_point(class_scope:page.TimeRange)
  ))
_sym_db.RegisterMessage(TimeRange)

PageOption = _reflection.GeneratedProtocolMessageType('PageOption', (_message.Message,), dict(
  DESCRIPTOR = _PAGEOPTION,
  __module__ = 'page.page_pb2'
  # @@protoc_insertion_point(class_scope:page.PageOption)
  ))
_sym_db.RegisterMessage(PageOption)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\025CsharpRPCLibrary.Grpc'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
